Repository livechat/design-system, pull requests merged in 2019-07, with the labels that each got.

#93 Added no wrap to toast action
  src/components/Toast/style.scss
Labels: needs review

#95 Release v0.4.3
  CHANGELOG.md
  package.json
Labels: needs review

#87 ButtonGroup component
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/ButtonGroup.md
  src/components/ButtonGroup/ButtonGroup.test.js
  src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
  src/components/ButtonGroup/index.js
  src/components/ButtonGroup/style.scss
  src/interfaces/buttonGroup.d.ts
  src/scss/variables/colors.scss
  styleguide.config.js
Labels: workshop

#100 Tooltip themes
  assets/tooltip_themes.png
  src/components/TooltipNew/CssTooltip.js
  src/components/TooltipNew/CssTooltip.md
  src/components/TooltipNew/PopperTooltip.js
  src/components/TooltipNew/PopperTooltip.md
  src/components/TooltipNew/design-guide.md
  src/components/TooltipNew/style.scss
  src/interfaces/tooltipNew.d.ts
  src/scss/variables/colors.scss
Labels: enhancement, needs review

#98 fixed btn line height
  src/components/Button/Button.js
  src/components/Button/__snapshots__/Button.test.js.snap
  src/components/Button/style.scss
Labels: ready for release

#96 fix radio button on ie11
  src/components/CheckboxField/style.scss
  src/components/RadioButton/style.scss
Labels: ready for release

#101 Introducing Guide Tooltips
  assets/sylvester.jpg
  src/components/TooltipNew/SpotlightOverlay.js
  src/components/TooltipNew/UserGuideTooltip.js
  src/components/TooltipNew/UserGuideTooltip.md
  src/components/TooltipNew/index.js
  src/components/TooltipNew/style.scss
  src/components/index.js
  src/helpers/virtual-element-reference.js
  src/interfaces/tooltipNew.d.ts
  styleguide.config.js
Labels: needs review, partial
