Repository livechat/design-system, pull requests merged in 2019-09, with the labels that each got.

#117 Guide Tooltips > Make spotlight non-clickable
  src/components/TooltipNew/SpotlightOverlay.js
  src/components/TooltipNew/UserGuideTooltip.js
  src/interfaces/tooltipNew.d.ts
Labels: needs review

#118 Release 0.4.6
  CHANGELOG.md
  package.json
  src/components/Button/style.scss
  src/components/Card/style.scss
  src/components/Modal/ModalBase.js
Labels: READY FOR REVIEW

#122 Feature/DS-76 Fixing button line-height, adding svg icon support
  src/components/Button/Button.js
  src/components/Button/Button.md
  src/components/Button/style.scss
  src/interfaces/buttons.d.ts
Labels: READY FOR REVIEW

#123 Release 0.5.0
  CHANGELOG.md
  docs/customized-components/Button.js
  package.json
  src/components/Button/Button.js
  src/components/Button/Button.md
  src/components/Button/style.scss
  src/components/ButtonGroup/ButtonGroup.js
  src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
  src/components/ButtonGroup/style.scss
  src/components/InAppMessage/InAppMessageFooter.js
  src/docs/ComponentHtmlMarkup.js
  src/interfaces/buttons.d.ts
  src/interfaces/tooltip.d.ts
Labels: READY FOR REVIEW

#124 Tooltips > Close with X button
  src/components/TooltipNew/CssTooltip.js
  src/components/TooltipNew/PopperTooltip.js
  src/components/TooltipNew/PopperTooltip.md
  src/components/TooltipNew/style.scss
  src/interfaces/tooltipNew.d.ts
Labels: ready for release

#119 Guide Tooltips > Overlay z-index
  src/components/Modal/ModalPortal.js
  src/components/TooltipNew/UserGuideTooltip.js
Labels: question, ready for release

#126 Release 0.5.1
  CHANGELOG.md
  package.json
  src/components/Modal/ModalPortal.js
  src/components/TooltipNew/CssTooltip.js
  src/components/TooltipNew/PopperTooltip.js
  src/components/TooltipNew/PopperTooltip.md
  src/components/TooltipNew/UserGuideTooltip.js
  src/components/TooltipNew/style.scss
  src/interfaces/tooltipNew.d.ts
Labels: READY FOR REVIEW

#120 Feature/DS-100 Upload components
  setup.js
  src/components/CollapseIcon/CollapseIcon.js
  src/components/CollapseIcon/index.js
  src/components/CollapseIcon/style.scss
  src/components/Progress/ProgressBar.js
  src/components/Progress/ProgressBar.md
  src/components/Progress/ProgressCircle.js
  src/components/Progress/ProgressCircle.md
  src/components/Progress/constants.js
  src/components/Progress/helpers.js
  src/components/Progress/index.js
  src/components/Progress/style.scss
  src/components/UploadBar/FileUploadProgress.js
  src/components/UploadBar/FileUploadProgress.md
  src/components/UploadBar/UploadBar.js
  src/components/UploadBar/UploadBar.md
  src/components/UploadBar/constants.js
  src/components/UploadBar/index.js
  src/components/UploadBar/style.scss
  src/components/index.js
  src/docs/PdfIcon.js
  src/interfaces/index.d.ts
  src/interfaces/progress.d.ts
  src/scss/mixins/button.scss
  styleguide.config.js
Labels: READY FOR REVIEW
