Repository livechat/design-system, pull requests merged in 2019-08, with the labels that each got.

#102 added missing interfaces for form
  src/interfaces/forms.d.ts
Labels: needs review

#105 handle error in field group
  src/components/FieldGroup/FieldGroup.js
  src/interfaces/forms.d.ts
Labels: ready for release

#107 Numeric input html improvement
  src/components/NumericInputField/NumericInput.js
  src/components/NumericInputField/__snapshots__/NumericInput.test.js.snap
Labels: READY FOR REVIEW

#106 Change checkbox structure to allow good work for alone HTML/CSS
  src/components/CheckboxField/Checkbox.js
  src/components/CheckboxField/style.scss
Labels: READY FOR REVIEW

#108 Guide Tooltips > Allow custom scrollable wrapper
  src/components/TooltipNew/UserGuideTooltip.js
  src/interfaces/tooltipNew.d.ts
Labels: needs review

#109 allow passing refs down to primitive element in TextArea and TextArea…
  src/components/TextAreaField/TextArea.js
  src/components/TextAreaField/TextAreaField.js
  src/interfaces/forms.d.ts
Labels: READY FOR REVIEW

#114 changed compact btn font size to 15px
  src/components/Button/style.scss
Labels: READY FOR REVIEW

#115 close modal on mousedown
  src/components/Modal/ModalBase.js
Labels: READY FOR REVIEW
