Repository livechat/design-system, pull requests merged in 2020-06, with the labels that each got.

#188 PP-2458 - text button
  docs/ComponentHtmlMarkup.js
  docs/customized-components/Button.js
  package-lock.json
  packages/colors/package-lock.json
  packages/design-system/src/components/Button/Button.js
  packages/design-system/src/components/Button/Button.md
  packages/design-system/src/components/Button/Button.test.js
  packages/design-system/src/components/Button/ButtonIcon.js
  packages/design-system/src/components/Button/ButtonIcon.test.js
  packages/design-system/src/components/Button/__snapshots__/Button.test.js.snap
  packages/design-system/src/components/Button/__snapshots__/ButtonIcon.test.js.snap
  packages/design-system/src/components/Button/style.scss
  packages/design-system/src/components/ButtonGroup/ButtonGroup.js
  packages/design-system/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
  packages/design-system/src/components/Form/Form.md
  packages/design-system/src/components/InAppMessage/InAppMessageBase.md
  packages/design-system/src/components/Modal/ActionModal.md
  packages/design-system/src/components/Modal/Modal.md
  packages/design-system/src/components/Progress/ProgressBar.md
  packages/design-system/src/components/Progress/ProgressCircle.md
  packages/design-system/src/components/TooltipNew/CssTooltip.md
  packages/design-system/src/components/TooltipNew/UserGuideTooltip.md
  packages/design-system/src/components/UploadBar/FileUploadProgress.md
  packages/design-system/src/components/UploadBar/UploadBar.md
  packages/design-system/src/interfaces/buttons.d.ts
  packages/design-system/src/interfaces/tooltip.d.ts
Labels: ready for release

#187 banner notification component
  packages/design-system/src/components/Banner/Banner.js
  packages/design-system/src/components/Banner/Banner.md
  packages/design-system/src/components/Banner/Banner.test.js
  packages/design-system/src/components/Banner/BannerIcon.js
  packages/design-system/src/components/Banner/__snapshots__/Banner.test.js.snap
  packages/design-system/src/components/Banner/index.js
  packages/design-system/src/components/Banner/style.scss
  packages/design-system/src/components/DatePicker/DatePicker.md
  packages/design-system/src/components/MultiSelectField/MultiSelect.md
  packages/design-system/src/components/SelectField/SelectField.md
  packages/design-system/src/components/index.js
  packages/design-system/src/interfaces/banner.d.ts
  styleguide.config.js
Labels: READY FOR REVIEW

#190 Banners promo
  packages/design-system/src/components/Promo/Promo.js
  packages/design-system/src/components/Promo/Promo.md
  packages/design-system/src/components/Promo/Promo.test.js
  packages/design-system/src/components/Promo/__snapshots__/Promo.test.js.snap
  packages/design-system/src/components/Promo/index.js
  packages/design-system/src/components/Promo/style.scss
  packages/design-system/src/interfaces/promo.d.ts
  styleguide.config.js
Labels: READY FOR REVIEW

#196 Improving css styles of Promo component
  packages/design-system/src/components/Promo/style.scss
Labels: READY FOR REVIEW, partial

#195 promo design review
  packages/design-system/src/components/Promo/style.scss
Labels: READY FOR REVIEW

#197 promo design review v2
  packages/design-system/package.json
  packages/design-system/src/components/Banner/Banner.md
  packages/design-system/src/components/Banner/style.scss
  packages/design-system/src/components/Promo/Promo.js
  packages/design-system/src/components/Promo/Promo.md
  packages/design-system/src/components/Promo/__snapshots__/Promo.test.js.snap
  packages/design-system/src/components/Promo/style.scss
Labels: READY FOR REVIEW
