Repository livechat/design-system, pull requests merged in 2023-05, with the labels that each got.

#529 DS-260 - New tokens values
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/light.scss
Labels: feature

#534 New icons
  packages/icons/svg/tabler/filetype-exe.svg
  packages/icons/svg/tabler/filetype-html.svg
  packages/icons/svg/tabler/filetype-jpg.svg
  packages/icons/svg/tabler/filetype-mp3.svg
  packages/icons/svg/tabler/filetype-other.svg
  packages/icons/svg/tabler/filetype-pdf.svg
  packages/icons/svg/tabler/filetype-ppt.svg
  packages/icons/svg/tabler/filetype-txt.svg
  packages/icons/svg/tabler/filetype-video.svg
  packages/icons/svg/tabler/filetype-xls.svg
  packages/icons/svg/tabler/filetype-zip.svg
  packages/icons/svg/tabler/logout-filled.svg
  packages/icons/svg/tabler/logout.svg
Labels: feature

#537 Added missing ActionMenu export
  packages/react-components/src/index.ts
Labels: bug

#538 Alert - component api docs update
  packages/react-components/src/components/Alert/Alert.module.scss
  packages/react-components/src/components/Alert/Alert.stories.tsx
  packages/react-components/src/components/Alert/Alert.tsx
Labels: bug, documentation

#541 Button - component api docs update
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Button/Button.tsx
Labels: documentation

#542 #536 - Popover - Add param to disable closing by esc press, docs update
  packages/react-components/src/components/Popover/Popover.stories.tsx
  packages/react-components/src/components/Popover/Popover.tsx
Labels: feature, documentation

#545 #535 - Picker - Added possibility to hide clear button, docs improvements
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/Trigger.tsx
Labels: feature, documentation

#544 #543 - Button - Create Float button
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Button/Button.tsx
Labels: feature, documentation

#547 #546 - Alert - Improvements: optional CTA buttons, documentation update
  packages/react-components/src/components/Alert/Alert.module.scss
  packages/react-components/src/components/Alert/Alert.spec.tsx
  packages/react-components/src/components/Alert/Alert.stories.tsx
  packages/react-components/src/components/Alert/Alert.tsx
  packages/react-components/src/foundations/spacing.css
Labels: feature, documentation

#564 #548 - Button - New button variant, UI fixes
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Button/Button.tsx
Labels: feature, documentation
