Repository livechat/design-system, pull requests merged in 2023-10, with the labels that each got.

#803 #757 - Tag - New size and spacing fixes
  packages/react-components/src/components/Tag/Tag.module.scss
  packages/react-components/src/components/Tag/Tag.stories.tsx
  packages/react-components/src/components/Tag/Tag.tsx
Labels: feature, design

#809 Switch - fix for controlled component mode
  packages/react-components/src/components/Switch/Switch.spec.tsx
  packages/react-components/src/components/Switch/Switch.tsx
Labels: bug

#813 #808 - Badge - Changes to small size
  packages/react-components/src/components/Badge/Badge.module.scss
Labels: design

#812 #807 - ActionMenu - Group header styles change, improved logic for keyboard control
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
Labels: bug, design

#818 #768 - Picker - Fix for TS error when input is empty and no item is selected
  packages/react-components/src/components/Picker/PickerList.tsx
Labels: bug

#821 #820 - Picker - Fix for keyboard control issue after filtering the list
  packages/react-components/src/components/Picker/PickerList.tsx
Labels: bug

#822 DS-806: Adding new icons; renaming a few existing
  packages/icons/entryConfig.ts
  packages/icons/package.json
  packages/icons/svg/CHIP_copilot_colored.svg
  packages/icons/svg/CHIP_copilot_mono.svg
  packages/icons/svg/alert-spam-filled.svg
  packages/icons/svg/alert-spam.svg
  packages/icons/svg/android-colored.svg
  packages/icons/svg/android.svg
  packages/icons/svg/android_colored.svg
  packages/icons/svg/bookmark-filled.svg
  packages/icons/svg/bookmark.svg
  packages/icons/svg/chat_bot_colored.svg
  packages/icons/svg/chat_bot_mono.svg
  packages/icons/svg/help_desk_colored.svg
  packages/icons/svg/help_desk_mono.svg
  packages/icons/svg/knowledge_base_colored.svg
  packages/icons/svg/knowledge_base_mono.svg
  packages/icons/svg/live_chat_colored.svg
  packages/icons/svg/live_chat_mono.svg
  packages/icons/svg/messages-filled.svg
  packages/icons/svg/messages.svg
  packages/icons/svg/messenger.svg
  packages/icons/svg/mood_angry.svg
  packages/icons/svg/open_widget_colored.svg
  packages/icons/svg/open_widget_mono.svg
  packages/icons/svg/report-filled.svg
  packages/icons/svg/report.svg
  packages/icons/svg/wand-filled.svg
  packages/icons/svg/wand.svg
Labels: design

#825 DS-824: Adding new icons
  packages/example-react/src/App.tsx
  packages/example-react/tsconfig.json
  packages/example-react/vite.config.ts
  packages/icons/entryConfig.ts
  packages/icons/package.json
  packages/icons/svg/add_emoji.svg
  packages/icons/svg/ai_summary-filled.svg
  packages/icons/svg/ai_summary.svg
  packages/icons/svg/instagram.svg
  packages/icons/svg/instagram_colored.svg
  packages/icons/svg/line.svg
  packages/icons/svg/line_colored.svg
  packages/icons/svg/repeat.svg
  packages/icons/svg/replace.svg
  packages/react-components/src/components/Tag/index.ts
  packages/react-components/tsconfig.json
Labels: feature, design

#814 #802 - DetailsCard - New component dedicated to details section
  packages/react-components/src/components/ActionMenu/index.ts
  packages/react-components/src/components/Button/Button.tsx
  packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
  packages/react-components/src/components/DetailsCard/DetailsCard.spec.tsx
  packages/react-components/src/components/DetailsCard/DetailsCard.stories.css
  packages/react-components/src/components/DetailsCard/DetailsCard.stories.tsx
  packages/react-components/src/components/DetailsCard/DetailsCard.tsx
  packages/react-components/src/components/DetailsCard/index.ts
  packages/react-components/src/components/DetailsCardInfo/DetailsCardInfo.module.scss
  packages/react-components/src/components/DetailsCardInfo/DetailsCardInfo.tsx
  packages/react-components/src/components/DetailsCardInfo/index.ts
  packages/react-components/src/index.ts
  packages/react-components/src/stories/assets/clock-light.svg
Labels: feature

#829 fix(DesignToken): adding missing colour token
  packages/react-components/src/themes/design-token.ts
Labels: bug

#834 fix(DesignToken): adding missing color token
  packages/react-components/src/themes/design-token.ts
Labels: bug

#836 docs(readme): Updating contribution and release docs
  README.md
  docs/RELEASE.md
  docs/assets/deploy_example.png
  package.json
Labels: documentation

#839 fix(Toast): Changes in close button
  packages/react-components/src/components/Toast/Toast.module.scss
  packages/react-components/src/components/Toast/Toast.tsx
Labels: bug

#841 fix(Tooltip): Changes in close button
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
  packages/react-components/src/components/Tooltip/components/Info.tsx
  packages/react-components/src/components/Tooltip/components/Interactive.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/UserGuideStep.tsx
Labels: bug

#842 fix(SegmentedControl): Remove divider
  packages/react-components/src/components/SegmentedControl/SegmentedControl.module.scss
Labels: bug

#846 fix(ActionMenu): Change divider position after element with this flag
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/constants.tsx
Labels: bug

#847 fix(DesignToken): updating color tokens
  packages/react-components/package.json
  packages/react-components/scripts/generateDesignTokenEnum.js
  packages/react-components/src/stories/components/ColorTokens.tsx
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/design-token.ts
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: bug, design

#849 build(deps): removing unused babel dev deps
  package-lock.json
  packages/react-components/package.json
Labels: dependencies

#851 fix(Tooltip): Fix for floating element wrong placement
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/components/FloatingComponent.tsx
Labels: bug

#853 feat(Icons): LC-786: adding new icons
  packages/icons/entryConfig.ts
  packages/icons/package.json
  packages/icons/svg/cloud-filled.svg
  packages/icons/svg/cloud.svg
  packages/icons/svg/key.svg
  packages/icons/svg/shield_lock-filled.svg
  packages/icons/svg/shield_lock.svg
  packages/icons/svg/source_code.svg
  packages/icons/svg/telegram_colored.svg
  packages/icons/svg/telegram_mono.svg
Labels: design

#854 feat(DesignToken): adding helper to set opacity for DesignToken color
  packages/react-components/src/index.ts
  packages/react-components/src/utils/getDesignTokenWithOpacity.ts
  packages/react-components/src/utils/index.ts
Labels: feature

#858 fix(Avatar): Disable user select on avatar component
  packages/react-components/src/components/Avatar/Avatar.module.scss
Labels: bug

#857 fix(PromoBannerV2): moving className prop to parent element
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
Labels: bug

#860 fix(Picker): Remove blue notch from selected item in a picker list
  packages/react-components/src/components/Picker/PickerList.module.scss
Labels: design

#859 feat(Button): Add new link-inverted button kind
  package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Button/Button.tsx
  packages/react-components/src/components/Button/helpers.ts
  packages/react-components/src/components/Button/index.ts
  packages/react-components/src/components/Button/types.ts
  packages/react-components/src/stories/components/StoryDescriptor.tsx
Labels: design

#862 fix(EmailTagInput): Passing props to TagInput component
  packages/react-components/src/components/TagInput/EmailTagInput.tsx
  packages/react-components/src/components/TagInput/TagInput.tsx
Labels: bug

#865 fix(Icons): updating a few icons
  packages/icons/svg/people-filled.svg
  packages/icons/svg/report-filled.svg
  packages/icons/svg/settings-filled.svg
  packages/icons/svg/settings.svg
Labels: design

#863 feat(TagInput): Add tag on blur
  packages/react-components/src/components/TagInput/TagInput.tsx
Labels: bug

#867 feat(ShadowToken): adding new shadow tokens
  packages/react-components/src/foundations/shadow-token.ts
  packages/react-components/src/foundations/shadow.css
Labels: design

#870 fix(Button): #861 - update active and focus states
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Button/Button.tsx
  packages/react-components/src/components/Button/styles/base.scss
  packages/react-components/src/components/Button/styles/icon.scss
  packages/react-components/src/components/Button/styles/kind.scss
  packages/react-components/src/components/Button/styles/loader.scss
  packages/react-components/src/components/Button/styles/size.scss
Labels: design

#871 docs(PromoBanner): add information about component deprecation
  packages/react-components/src/components/PromoBanner/PromoBanner.mdx
  packages/react-components/src/components/PromoBanner/PromoBanner.tsx
Labels: documentation
