Repository livechat/design-system, pull requests merged in 2023-06, with the labels that each got.

#579 DS-276: Adding new icons
  packages/icons/svg/tabler/facebook-filled.svg
  packages/icons/svg/tabler/facebook.svg
  packages/icons/svg/tabler/linux-filled.svg
  packages/icons/svg/tabler/linux.svg
  packages/icons/svg/tabler/twitter-filled.svg
  packages/icons/svg/tabler/twitter.svg
Labels: feature

#580 #553 - Input - UI fixes + docs update
  packages/react-components/src/components/Input/Input.module.scss
  packages/react-components/src/components/Input/Input.stories.tsx
  packages/react-components/src/components/Input/Input.tsx
Labels: bug, feature, documentation

#581 #552 - Tag/Email Input - UI fixes + docs update
  packages/react-components/src/components/TagInput/TagInput.module.scss
  packages/react-components/src/components/TagInput/TagInput.tsx
Labels: bug, documentation

#582 DS-276: new Linux icons
  packages/icons/svg/tabler/linux-filled.svg
  packages/icons/svg/tabler/linux.svg
Labels: design

#571 #569 - Picker - Adding dark mode support for scrollbars
  packages/react-components/.storybook/preview.js
  packages/react-components/src/components/Picker/PickerList.module.scss
  packages/react-components/src/foundations/color-scheme.css
  packages/react-components/src/index.scss
Labels: bug, design

#572 #561 - Tag - UI fixes, docs update
  packages/react-components/src/components/Tag/Tag.module.scss
  packages/react-components/src/components/Tag/Tag.stories.tsx
  packages/react-components/src/components/Tag/Tag.tsx
Labels: bug, documentation

#585 #551 - DatePciker - UI fixes
  packages/react-components/src/components/DatePicker/DatePicker.module.scss
Labels: bug

#583 570: Tooltip - disabling clicks on tooltip during animations
  packages/react-components/src/components/Tooltip/Tooltip.tsx
Labels: bug

#584 573: reacting properly on closeOnEsc prop change
  packages/react-components/src/components/Popover/Popover.tsx
Labels: bug

#587 #559 - Search - UI fixes + docs update
  packages/react-components/src/components/Search/Search.module.scss
  packages/react-components/src/components/Search/Search.tsx
Labels: bug, documentation

#588 #560 - SegmentedControl - UI fixes + docs update
  packages/react-components/src/components/SegmentedControl/SegmentedControl.module.scss
  packages/react-components/src/components/SegmentedControl/SegmentedControl.tsx
Labels: bug, documentation

#593 577: Improving paddings for Trigger and TriggerBody components
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/Trigger.module.scss
  packages/react-components/src/components/Picker/TriggerBody.module.scss
Labels: design

#592 DS-273: adding openedOnInit prop; passthrough of the data-testid prop to trigger element
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/Trigger.tsx
Labels: bug, feature, documentation

#589 #558 - PromoBanner - UI fixes + docs update
  packages/react-components/src/components/PromoBanner/PromoBanner.module.scss
  packages/react-components/src/components/PromoBanner/PromoBanner.tsx
Labels: bug, documentation

#594 426: DevEx Improvements in Input and Tag Input components
  packages/react-components/src/components/Input/Input.spec.tsx
  packages/react-components/src/components/Input/Input.tsx
  packages/react-components/src/components/TagInput/TagInput.tsx
Labels: bug

#595 573: Popover - fix for closeOnEsc prop
  packages/react-components/src/components/Popover/Popover.tsx
Labels: bug

#596 521: Picker - setting horizontal scroll in PickerList as auto
  packages/react-components/src/components/Picker/PickerList.module.scss
Labels: design

#598 597: Tooltip - onOpen, onClose fixes
  packages/react-components/src/components/Tooltip/Tooltip.spec.tsx
  packages/react-components/src/components/Tooltip/Tooltip.tsx
Labels: bug

#603 #601 - Picker - Update box-shadow value
  packages/react-components/src/components/Picker/PickerList.module.scss
Labels: bug

#608 #562 - Tooltip - Ui fixes
  packages/react-components/src/components/Tooltip/Interactive.tsx
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
Labels: bug

#610 #549 - Checkbox - UI fixes
  packages/react-components/src/components/FieldDescription/FieldDescription.module.scss
Labels: bug

#602 Storybook update
  package-lock.json
  packages/example-react/package-lock.json
  packages/example-react/package.json
  packages/icons/package-lock.json
  packages/react-components/.storybook/main.js
  packages/react-components/package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/ActionMenu/ActionMenu.mdx
  packages/react-components/src/components/Toast/ToastWrapper.tsx
  packages/react-components/vite.config.ts
Labels: dependencies, documentation

#607 Icons docs update
  package-lock.json
  package.json
  packages/react-components/src/components/Icon/Icon.stories.tsx
  packages/react-components/src/stories/Icons.stories.mdx
  packages/react-components/src/stories/TablerIcons.stories.mdx
Labels: feature, documentation

#606 #555 - Progress - UI fixes + docs update
  packages/react-components/src/components/FileUploadProgress/FileUploadProgress.stories.tsx
  packages/react-components/src/components/FileUploadProgress/FileUploadProgress.tsx
  packages/react-components/src/components/Loader/Loader.module.scss
  packages/react-components/src/components/Loader/Loader.stories.tsx
  packages/react-components/src/components/Loader/Loader.tsx
  packages/react-components/src/components/Progress/ProgressBar.tsx
  packages/react-components/src/components/Progress/ProgressCircle.stories.tsx
  packages/react-components/src/components/Progress/ProgressCircle.tsx
  packages/react-components/src/components/UploadBar/UploadBar.module.scss
  packages/react-components/src/components/UploadBar/UploadBar.tsx
Labels: bug, documentation

#612 #554 - FormField - UI fixes, docs update
  packages/react-components/src/components/FieldError/FieldError.module.scss
  packages/react-components/src/components/FieldError/FieldError.tsx
  packages/react-components/src/components/FormField/FormField.module.scss
  packages/react-components/src/components/FormField/FormField.stories.tsx
  packages/react-components/src/components/FormField/FormField.tsx
Labels: bug, documentation

#609 Chromatic TurboSnap feature
  .github/workflows/chromatic.yml
  packages/react-components/package-lock.json
  packages/react-components/package.json
  packages/react-components/vite.config.ts
Labels: feature, dependencies

#615 Updating color token for plain button
  packages/react-components/src/components/Button/Button.module.scss
Labels: design

#617 Updating content-basic-gradient-01 token for Legacy theme
  packages/react-components/src/themes/legacy.scss
Labels: design

#618 Updating color token for light theme
  packages/react-components/src/themes/light.scss
Labels: design

#619 Adding new color tokens: SurfaceGradient01 and SurfaceGradient02
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/design-token.ts
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#616 Updating "Check" icon color for selected Picker Item
  packages/react-components/src/components/Picker/PickerList.tsx
Labels: design

#621 Avoid redundand calls of onOpen and onClose callbacks
  packages/react-components/src/components/Tooltip/Tooltip.spec.tsx
  packages/react-components/src/components/Tooltip/Tooltip.tsx
Labels: bug

#623 Firing open-close callbacks for managed components
  packages/react-components/src/components/Tooltip/Tooltip.tsx
Labels: bug
