Repository livechat/design-system, pull requests merged in 2023-09, with the labels that each got.

#756 #486 - Tag - Option set icon on the left/right side
  packages/react-components/src/components/Tag/Tag.module.scss
  packages/react-components/src/components/Tag/Tag.stories.tsx
  packages/react-components/src/components/Tag/Tag.tsx
Labels: feature

#759 Modify `getInitials` so it ignores middle names
  packages/react-components/src/components/Avatar/Avatar.helpers.spec.ts
  packages/react-components/src/components/Avatar/Avatar.helpers.ts
Labels: feature

#760 Adding/updating color tokens
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#761 Possible fix for 744
  packages/react-components/src/components/Picker/PickerList.tsx
Labels: bug

#741 #671 Add new options to Picker
  packages/react-components/src/components/Modal/StoriesComponents.tsx
  packages/react-components/src/components/Picker/Picker.spec.tsx
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/PickerList.module.scss
  packages/react-components/src/components/Picker/PickerList.spec.tsx
  packages/react-components/src/components/Picker/PickerList.tsx
  packages/react-components/src/components/Picker/PickerListItem.tsx
  packages/react-components/src/components/Picker/TriggerBody.module.scss
  packages/react-components/src/components/Picker/TriggerBody.spec.tsx
  packages/react-components/src/components/Picker/TriggerBody.tsx
  packages/react-components/src/components/Picker/constants.ts
  packages/react-components/src/components/Picker/helpers.ts
  packages/react-components/src/components/Picker/index.ts
  packages/react-components/src/components/Picker/types.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#733 [Action Bar] - MVP experimental new component
  packages/react-components/src/components/ActionBar/ActionBar.module.scss
  packages/react-components/src/components/ActionBar/ActionBar.spec.tsx
  packages/react-components/src/components/ActionBar/ActionBar.stories.tsx
  packages/react-components/src/components/ActionBar/ActionBar.tsx
  packages/react-components/src/components/ActionBar/ActionBarItem.tsx
  packages/react-components/src/components/ActionBar/index.ts
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/Popover/Popover.module.scss
  packages/react-components/src/components/Popover/Popover.tsx
  packages/react-components/src/index.ts
Labels: feature

#766 Updating content secondary token
  packages/react-components/src/themes/light.scss
Labels: design

#772 Fix for import issue in Icon component
  lerna.json
  package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/Icon/Icon.tsx
  packages/react-components/src/components/Icon/index.ts
  packages/react-components/src/components/Icon/types.ts
  packages/react-components/src/components/Picker/types.ts
  packages/react-components/src/components/UploadBar/UploadBar.stories.tsx
Labels: bug

#776 [Modal] Add content class prop
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Modal/StoriesComponents.tsx
  packages/react-components/src/components/Modal/components/ModalBase.spec.tsx
  packages/react-components/src/components/Modal/components/ModalBase.tsx
  packages/react-components/src/components/Modal/components/ModalCloseButton.tsx
  packages/react-components/src/components/Modal/components/ModalHeader.module.scss
  packages/react-components/src/components/Modal/components/ModalHeader.tsx
  packages/react-components/src/components/Modal/components/ModalPortal.tsx
  packages/react-components/src/components/Modal/index.ts
  packages/react-components/src/stories/assets/modal-image.png
Labels: bug, feature

#775 [ActionMenu] - fixes after RefreshUI tests
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.css
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/ActionMenu/types.ts
  packages/react-components/src/components/Picker/PickerList.module.scss
  packages/react-components/src/components/Popover/Popover.module.scss
Labels: bug, feature

#779 Replacing leftIcon, rightIcon, avatar props with leftNode and rightNode
  packages/react-components/src/components/Tag/Tag.mdx
  packages/react-components/src/components/Tag/Tag.module.scss
  packages/react-components/src/components/Tag/Tag.spec.tsx
  packages/react-components/src/components/Tag/Tag.stories.tsx
  packages/react-components/src/components/Tag/Tag.tsx
Labels: feature

#783 [Color tokens] - Update avatars colors
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#784 #781 - [ActionMenu] - Fix for selecting items by keyboard logic
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
Labels: bug

#788 #787 [Picker] - ui fix for small container
  packages/react-components/src/components/Picker/TriggerBody.module.scss
  packages/react-components/src/components/Picker/TriggerBody.tsx
Labels: bug

#791 #789 #790 [Avatar] Return color based on text, not initials. Apply background color only in case of image type
  packages/react-components/src/components/Avatar/Avatar.helpers.spec.ts
  packages/react-components/src/components/Avatar/Avatar.helpers.ts
  packages/react-components/src/components/Avatar/Avatar.tsx
Labels: bug

#786 #785 - Documentation page for radius tokens
  packages/react-components/src/stories/Radius.stories.mdx
  packages/react-components/src/stories/components/Radius.tsx
  packages/react-components/src/stories/components/RadiusExamples.module.scss
  packages/react-components/src/stories/components/RadiusExamples.tsx
  packages/react-components/src/stories/components/Spacing.tsx
  packages/react-components/src/stories/components/Table.css
Labels: documentation

#796 [Avatar] - Fix for moving avatar when rim is visible
  packages/react-components/src/components/Avatar/Avatar.module.scss
Labels: bug

#800 #773 - New gradient tokens
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#798 #771 - Tag - Close icon size change for small component
  packages/react-components/src/components/Tag/Tag.stories.tsx
  packages/react-components/src/components/Tag/Tag.tsx
Labels: bug

#797 #769 - Icons update
  packages/icons/svg/tabler/alert-spam-filled.svg
  packages/icons/svg/tabler/alert-spam.svg
  packages/icons/svg/tabler/facebook-colored.svg
  packages/icons/svg/tabler/facebook-filled.svg
  packages/icons/svg/tabler/facebook.svg
  packages/icons/svg/tabler/messages-filled.svg
  packages/icons/svg/tabler/messages.svg
  packages/icons/svg/tabler/messenger-colored.svg
  packages/icons/svg/tabler/messenger.svg
  packages/icons/svg/tabler/report-filled.svg
  packages/icons/svg/tabler/report.svg
Labels: feature

#795 #794 [ActionBar] - Fixes with different button types
  packages/react-components/src/components/ActionBar/ActionBar.module.scss
  packages/react-components/src/components/ActionBar/ActionBar.stories.tsx
  packages/react-components/src/components/ActionBar/ActionBarItem.tsx
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/types.ts
Labels: bug

#793 [Modal] - Label heading fix for "full space content" Modal type + Avatar in the modal header
  packages/react-components/src/components/Avatar/index.ts
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/components/Modal/Modal.stories.css
  packages/react-components/src/components/Modal/Modal.stories.tsx
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Modal/components/ModalHeader.module.scss
  packages/react-components/src/components/Modal/components/ModalHeader.tsx
Labels: bug, feature
