Repository livechat/design-system, pull requests merged in 2023-08, with the labels that each got.

#711 #710 - Popover - Fix for missing token value used as background color
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: bug, design

#705 #696 - Avatar - Changes in avatar sizes
  packages/react-components/src/components/Avatar/Avatar.module.scss
  packages/react-components/src/components/Avatar/Avatar.stories.tsx
  packages/react-components/src/components/Avatar/Avatar.tsx
Labels: feature, design

#717 Linters update
  .eslintignore
  .prettierignore
  .stylelintignore
  .stylelintrc.json
  package-lock.json
  package.json
  packages/react-components/src/components/FieldGroup/FieldGroup.module.scss
  packages/react-components/src/components/Icon/Icon.tsx
  packages/react-components/src/components/Picker/Picker.spec.tsx
  packages/react-components/src/components/Picker/PickerList.spec.tsx
  packages/react-components/src/components/Popover/Popover.stories.css
  packages/react-components/src/components/Tab/TabsWrapper.module.scss
  packages/react-components/src/components/Tooltip/components/FloatingComponent.tsx
  packages/react-components/src/components/Typography/Typography.module.scss
  packages/react-components/src/stories/components/ColorTokens.tsx
Labels: dependencies

#732 #723 - Button - New High Contrast Button variant, styles updates
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/Alert/Alert.module.scss
  packages/react-components/src/components/Alert/Alert.tsx
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Button/Button.tsx
  packages/react-components/src/components/Card/Card.tsx
  packages/react-components/src/components/Input/Input.tsx
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/components/Modal/Modal.stories.tsx
  packages/react-components/src/components/Modal/ModalCloseButton.tsx
  packages/react-components/src/components/PromoBanner/PromoBanner.tsx
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
  packages/react-components/src/components/Search/Search.module.scss
  packages/react-components/src/components/Search/Search.tsx
  packages/react-components/src/components/Toast/Toast.module.scss
  packages/react-components/src/components/Toast/Toast.tsx
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
  packages/react-components/src/components/Tooltip/components/Info.tsx
  packages/react-components/src/components/Tooltip/components/Interactive.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/UserGuideStep.tsx
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: feature, design

#735 #726 - Alert - Change buttons kind
  packages/react-components/src/components/Alert/Alert.tsx
Labels: design

#742 Auto assign issues to the project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature.yml
Labels: feature

#739 #531 - Tooltip - Possibility to set display method for tooltip wrapper
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
  packages/react-components/src/components/Tooltip/Tooltip.tsx
Labels: bug

#740 #659 - New avatar color tokens
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#738 #351 - Input - Option to enable ellipsis in input
  packages/react-components/src/components/Input/Input.module.scss
  packages/react-components/src/components/Input/Input.tsx
Labels: feature

#746 Adding new icons
  packages/icons/svg/tabler/briefcase-filled.svg
  packages/icons/svg/tabler/briefcase.svg
  packages/icons/svg/tabler/target_arrow-filled.svg
  packages/icons/svg/tabler/target_arrow.svg
  packages/icons/svg/tabler/text_logo.svg
Labels: feature

#751 #748 - Tag - New size + documentation update
  packages/react-components/src/components/Tag/Tag.module.scss
  packages/react-components/src/components/Tag/Tag.stories.tsx
  packages/react-components/src/components/Tag/Tag.tsx
Labels: design

#752 #749 - Button - New variant
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Button/Button.tsx
Labels: design

#754 Fixing non-text content styling. Tooltip type exporting.
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Modal/StoriesComponents.tsx
  packages/react-components/src/components/Popover/Popover.stories.tsx
  packages/react-components/src/components/Popover/Popover.tsx
  packages/react-components/src/components/Toast/Toast.tsx
  packages/react-components/src/components/Toast/ToastWrapper.stories.tsx
  packages/react-components/src/components/Tooltip/index.ts
Labels: bug
