Repository livechat/design-system, pull requests merged in 2023-12, with the labels that each got.

#910 feat(MessageBox token): New messagebox token
  packages/react-components/src/foundations/shadow-token.ts
  packages/react-components/src/foundations/shadow.css
Labels: feature, design

#913 fix(DatePicker): fix for clsx import
  packages/react-components/src/components/DatePicker/DatePickerNavbar.tsx
  packages/react-components/src/components/DatePicker/DatePickerRangeCalendarsWrapper.tsx
  packages/react-components/src/components/DatePicker/helpers.ts
  packages/react-components/src/foundations/radius-token.ts
  packages/react-components/src/foundations/radius.css
  packages/react-components/src/foundations/spacing-token.ts
  packages/react-components/src/foundations/spacing.css
Labels: bug

#914 fix(DatePicker): fixing DatePickerRangeCalendarsWrapper export path
  packages/react-components/src/components/DatePicker/index.ts
Labels: bug

#915 feat(Tooltip): useClick hook props for Tooltip component
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/types.ts
Labels: feature

#918 feat(ActionMenu): Possibility to check the selected options
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
Labels: feature

#921 fix(DesignToken): updating SurfacePrimaryHover value for light theme
  packages/react-components/src/themes/light.scss
Labels: design

#922 fix(TransitionToken): Adding new delay tokens and Transition story
  packages/react-components/src/foundations/transition-token.ts
  packages/react-components/src/foundations/transition.css
  packages/react-components/src/index.ts
  packages/react-components/src/stories/Radius.stories.mdx
  packages/react-components/src/stories/Transition.stories.mdx
  packages/react-components/src/stories/components/Table.css
  packages/react-components/src/stories/components/Transition/TransitionTable.tsx
  packages/react-components/src/stories/components/Transition/transitionDelay.ts
  packages/react-components/src/stories/components/Transition/transitionDuration.ts
  packages/react-components/src/stories/components/Transition/transitionTiming.ts
Labels: documentation, design

#925 feat(PromoBannerV2): vertical mode, class name props for content containers
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.tsx
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
Labels: feature

#928 fix(Button): Fixing only-icon Button padding
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Button/styles/size.scss
Labels: bug, design

#929 feat(DetailsCard): Custom component as card label
  packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
  packages/react-components/src/components/DetailsCard/DetailsCard.stories.css
  packages/react-components/src/components/DetailsCard/DetailsCard.stories.tsx
  packages/react-components/src/components/DetailsCard/DetailsCard.tsx
Labels: feature

#930 feat(Icon): new adding new icons; moving a svgr config to a separate file
  packages/icons/.svgrrc.js
  packages/icons/entryConfig.ts
  packages/icons/package.json
  packages/icons/svg/arrow_fork.svg
  packages/icons/svg/book.svg
  packages/icons/svg/circle_minus.svg
  packages/icons/svg/clipboard_check.svg
  packages/icons/svg/clipboard_x.svg
  packages/icons/svg/currency_dollar.svg
  packages/icons/svg/rocket.svg
  packages/icons/svg/webhook.svg
Labels: feature

#931 fix(DesignToken): adding new token SurfacePrimaryHoverOpacity
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/design-token.ts
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#932 fix(Input): adding styling for readOnly input component
  packages/react-components/src/components/Input/Input.mdx
  packages/react-components/src/components/Input/Input.module.scss
  packages/react-components/src/components/Input/Input.stories.tsx
  packages/react-components/src/components/Input/Input.tsx
Labels: design

#939 fix(Button): Adding new size xcompact
  packages/react-components/.storybook/preview-head.html
  packages/react-components/src/components/Button/Button.mdx
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Button/Button.tsx
  packages/react-components/src/components/Button/styles/base.scss
  packages/react-components/src/components/Button/styles/icon.scss
  packages/react-components/src/components/Button/styles/size.scss
  packages/react-components/src/components/Button/types.ts
  packages/react-components/src/stories/components/StoryDescriptor.tsx
Labels: bug, documentation

#940 fix(Badge): Changing tertiary color
  .github/workflows/update-pr-description.yml
  packages/react-components/src/components/Badge/Badge.module.scss
Labels: bug, design
