Repository livechat/design-system, pull requests merged in 2023-07, with the labels that each got.

#630 Fixes for build process
  packages/react-components/package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/Popover/Popover.tsx
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/vite.config.ts
Labels: dependencies

#620 #557 - Picker - UI fixes
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/Trigger.module.scss
  packages/react-components/src/components/Picker/Trigger.tsx
  packages/react-components/src/components/Picker/TriggerBody.module.scss
  packages/react-components/src/components/Picker/TriggerBody.tsx
Labels: bug

#586 #551 - Modal - seperate header and footer components for modal
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/components/Modal/Modal.stories.tsx
  packages/react-components/src/components/Modal/ModalHeader.tsx
  packages/react-components/src/components/Modal/StoriesComponents.tsx
  packages/react-components/src/components/Modal/index.ts
Labels: feature, design

#629 #626 - Tooltip - UI fixes
  packages/react-components/src/components/Tooltip/Info.tsx
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
  packages/react-components/src/components/Tooltip/helpers.ts
Labels: bug, design

#628 #614 - Tabler icons in components
  packages/react-components/src/components/Alert/Alert.tsx
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Card/Card.tsx
  packages/react-components/src/components/FileUploadProgress/FileUploadProgress.tsx
  packages/react-components/src/components/FileUploadProgress/FileUploadProgressActions.module.scss
  packages/react-components/src/components/FileUploadProgress/FileUploadProgressActions.tsx
  packages/react-components/src/components/Icon/Icon.module.scss
  packages/react-components/src/components/Icon/Icon.tsx
  packages/react-components/src/components/Input/Input.stories.tsx
  packages/react-components/src/components/Input/Input.tsx
  packages/react-components/src/components/Loader/Loader.module.scss
  packages/react-components/src/components/Modal/ModalCloseButton.tsx
  packages/react-components/src/components/NumericInput/NumericInput.tsx
  packages/react-components/src/components/Picker/Trigger.tsx
  packages/react-components/src/components/Popover/Popover.stories.tsx
  packages/react-components/src/components/PromoBanner/PromoBanner.tsx
  packages/react-components/src/components/Search/Search.tsx
  packages/react-components/src/components/SegmentedControl/SegmentedControl.stories.tsx
  packages/react-components/src/components/Switch/Switch.tsx
  packages/react-components/src/components/Tag/Tag.stories.tsx
  packages/react-components/src/components/Tag/Tag.tsx
  packages/react-components/src/components/Toast/Toast.tsx
  packages/react-components/src/components/Tooltip/Info.tsx
  packages/react-components/src/components/Tooltip/Interactive.tsx
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
  packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
  packages/react-components/src/components/Tooltip/UserGuideStep.tsx
  packages/react-components/src/components/UploadBar/UploadBar.tsx
  packages/react-components/src/stories/Icons.stories.mdx
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#635 634: Checkbox mask size issue on Safari and Firefox
  packages/react-components/src/components/Checkbox/Checkbox.module.scss
Labels: bug, design

#639 637: ProgressCircle and ProgressBar UI improvements
  packages/react-components/src/components/Progress/ProgressBar.module.scss
  packages/react-components/src/components/Progress/ProgressCircle.module.scss
Labels: design

#636 Popover: replacing colour token
  packages/react-components/src/components/Popover/Popover.module.scss
Labels: design

#622 README update with the Rules of contribution
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#638 #625 - Typography tokens in components
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.css
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/ActionMenu/ActionMenuItem.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenuItem.tsx
  packages/react-components/src/components/ActionMenu/constants.tsx
  packages/react-components/src/components/Checkbox/Checkbox.module.scss
  packages/react-components/src/components/FileUploadProgress/FileUploadProgress.tsx
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Popover/Popover.tsx
  packages/react-components/src/components/Toast/Toast.tsx
  packages/react-components/src/components/UploadBar/UploadBar.tsx
Labels: design

#640 #591 - Reports tooltip component
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
  packages/react-components/src/components/Tooltip/Tooltip.stories.css
  packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/components/FloatingComponent.tsx
  packages/react-components/src/components/Tooltip/components/Reports.tsx
  packages/react-components/src/components/Tooltip/components/index.ts
  packages/react-components/src/components/Tooltip/index.ts
  packages/react-components/src/components/Tooltip/types.ts
Labels: feature, design

#643 #642 - Alert - New tokens for all alert kinds
  packages/react-components/src/components/Alert/Alert.module.scss
  packages/react-components/src/components/Alert/Alert.tsx
Labels: design

#645 ActionMenu - docs update
  packages/react-components/.storybook/main.js
  packages/react-components/package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/ActionMenu/ActionMenu.mdx
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.css
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/ActionMenu/ActionMenuItem.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenuItem.tsx
  packages/react-components/src/components/ActionMenu/constants.tsx
  packages/react-components/src/components/ActionMenu/index.ts
  packages/react-components/src/stories/components/BlockColumns.module.scss
  packages/react-components/src/stories/components/BlockColumns.tsx
Labels: documentation

#644 Feature/alert docs
  packages/example-react/package-lock.json
  packages/react-components/.storybook/main.js
  packages/react-components/package-lock.json
  packages/react-components/src/components/Alert/Alert.mdx
  packages/react-components/src/components/NumericInput/NumericInput.mdx
  packages/react-components/src/components/Picker/Picker.mdx
  packages/react-components/src/components/Picker/Picker.stories.tsx
Labels: documentation

#646 New Figma iFrame plugin
  packages/react-components/.storybook/main.js
  packages/react-components/package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/ActionMenu/ActionMenu.mdx
  packages/react-components/src/components/Alert/Alert.mdx
  packages/react-components/src/components/NumericInput/NumericInput.mdx
  packages/react-components/src/components/Picker/Picker.mdx
Labels: dependencies

#647 ActionMenu - Fix for documentation
  packages/react-components/src/components/ActionMenu/ActionMenu.mdx
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
Labels: bug, documentation

#648 Avatar - Docs update
  packages/react-components/src/components/Avatar/Avatar.mdx
Labels: documentation

#654 Fixing Checkbox component styling
  packages/react-components/src/components/Checkbox/Checkbox.module.scss
  packages/react-components/src/components/Checkbox/Checkbox.stories.tsx
Labels: documentation, design

#653 Card - Docs update
  packages/react-components/src/components/Card/Card.mdx
Labels: documentation

#652 Button - Docs update
  packages/react-components/src/components/Button/Button.mdx
Labels: documentation

#650 Improving storybook docs
  packages/react-components/src/components/Alert/Alert.mdx
  packages/react-components/src/components/NumericInput/NumericInput.mdx
  packages/react-components/src/components/Picker/Picker.mdx
  packages/react-components/src/components/Popover/Popover.mdx
  packages/react-components/src/components/Progress/ProgressBar.mdx
  packages/react-components/src/components/Progress/ProgressBar.stories.tsx
  packages/react-components/src/components/Progress/ProgressCircle.mdx
  packages/react-components/src/components/Progress/ProgressCircle.stories.tsx
  packages/react-components/src/components/PromoBanner/PromoBanner.mdx
  packages/react-components/src/components/PromoBanner/PromoBanner.stories.tsx
  packages/react-components/src/components/RadioButton/RadioButton.mdx
  packages/react-components/src/components/Search/Search.mdx
  packages/react-components/src/components/SegmentedControl/SegmentedControl.mdx
  packages/react-components/src/components/Switch/Switch.mdx
  packages/react-components/src/components/Tab/TabsWrapper.mdx
  packages/react-components/src/components/Tag/Tag.mdx
  packages/react-components/src/components/TagInput/TagInput.mdx
  packages/react-components/src/components/Textarea/Textarea.mdx
  packages/react-components/src/components/Toast/Toast.mdx
  packages/react-components/src/components/Tooltip/Tooltip.mdx
  packages/react-components/src/components/UploadBar/UploadBar.mdx
Labels: documentation

#656 Improving storybook docs
  packages/react-components/src/components/ActionMenu/ActionMenu.mdx
  packages/react-components/src/components/Avatar/Avatar.mdx
  packages/react-components/src/components/Badge/Badge.mdx
  packages/react-components/src/components/Button/Button.mdx
  packages/react-components/src/components/Card/Card.mdx
  packages/react-components/src/components/Checkbox/Checkbox.mdx
  packages/react-components/src/components/Checkbox/Checkbox.tsx
  packages/react-components/src/components/DatePicker/DatePicker.mdx
  packages/react-components/src/components/DatePicker/RangeDatePicker.mdx
  packages/react-components/src/components/Form/Form.tsx
  packages/react-components/src/components/FormGroup/FormGroup.tsx
  packages/react-components/src/components/Icon/Icon.mdx
  packages/react-components/src/components/Icon/Icon.tsx
  packages/react-components/src/components/Input/Input.mdx
  packages/react-components/src/components/Loader/Loader.mdx
  packages/react-components/src/components/Modal/Modal.mdx
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Modal/ModalBase.tsx
Labels: documentation

#661 Updating the README
  README.md
  packages/example-react/package-lock.json
Labels: documentation

#667 Update old docs
  README.md
  docs/customized-components/Menu.js
Labels: documentation

#690 #680 - Radius tokens
  packages/react-components/.storybook/preview.js
  packages/react-components/src/foundations/radius-token.ts
  packages/react-components/src/foundations/radius.css
  packages/react-components/src/index.scss
  packages/react-components/src/index.ts
Labels: feature, design

#694 #693 - Add mood icons
  packages/icons/svg/tabler/mood_empty.svg
  packages/icons/svg/tabler/mood_neutral.svg
  packages/icons/svg/tabler/mood_sad.svg
  packages/icons/svg/tabler/mood_very_sad.svg
Labels: feature

#660 #651 - Picker - Auto clear search option
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/TriggerBody.spec.tsx
  packages/react-components/src/components/Picker/TriggerBody.tsx
Labels: feature, design

#679 #670 - Toast - Spacing change
  packages/react-components/src/components/Toast/Toast.module.scss
Labels: design

#678 #566 - ActionMenu - Option to prevent closing when option is selected
  packages/react-components/src/components/ActionMenu/ActionMenu.spec.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/RadioButton/RadioButton.module.scss
Labels: feature, documentation

#691 #681 - Button - Updated button border radius
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/foundations/radius-token.ts
  packages/react-components/src/foundations/radius.css
Labels: design

#692 #682 - Update border-radius for components
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/Alert/Alert.module.scss
  packages/react-components/src/components/Card/Card.module.scss
  packages/react-components/src/components/DatePicker/DatePicker.module.scss
  packages/react-components/src/components/Input/Input.module.scss
  packages/react-components/src/components/NumericInput/NumericInput.module.scss
  packages/react-components/src/components/Popover/Popover.module.scss
  packages/react-components/src/components/Search/Search.module.scss
  packages/react-components/src/components/Textarea/Textarea.module.scss
  packages/react-components/src/components/Toast/Toast.module.scss
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
Labels: design

#700 #687 - Modal - Refreshed UI
  packages/react-components/src/components/Modal/Modal.mdx
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/components/Modal/Modal.spec.tsx
  packages/react-components/src/components/Modal/Modal.stories.tsx
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Modal/ModalBase.spec.tsx
  packages/react-components/src/components/Modal/ModalBase.tsx
  packages/react-components/src/components/Modal/ModalCloseButton.tsx
  packages/react-components/src/components/Modal/ModalHeader.module.scss
  packages/react-components/src/components/Modal/ModalHeader.tsx
  packages/react-components/src/components/Modal/StoriesComponents.tsx
  packages/react-components/src/foundations/spacing.css
Labels: design

#695 #685 - Picker - UI refresh
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/PickerList.module.scss
  packages/react-components/src/components/Picker/PickerList.tsx
  packages/react-components/src/components/Picker/PickerListItem.tsx
  packages/react-components/src/components/Picker/Trigger.module.scss
  packages/react-components/src/components/Picker/TriggerBody.module.scss
  packages/react-components/src/components/Picker/TriggerBody.tsx
  packages/react-components/src/components/Picker/types.ts
Labels: design

#698 Reverting Github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: documentation

#699 Upgrading Lerna and Storybook versions
  docs/RELEASE.md
  lerna.json
  nx.json
  package-lock.json
  package.json
  packages/example-react/package-lock.json
  packages/example-react/package.json
  packages/example-react/src/App.tsx
  packages/example-react/tsconfig.json
  packages/icons/package-lock.json
  packages/react-components/.storybook/main.js
  packages/react-components/package-lock.json
  packages/react-components/package.json
  packages/react-components/tsconfig.json
Labels: dependencies

#703 #688 - Segmented Control - UI Refresh
  packages/react-components/src/components/SegmentedControl/SegmentedControl.module.scss
Labels: design

#702 #689 - Tag input - UI refresh for tag input
  packages/react-components/src/components/TagInput/TagInput.module.scss
Labels: design

#701 Updating TSConfig and ESLint rules
  .eslintrc
  .prettierrc
  package-lock.json
  package.json
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/Alert/Alert.spec.tsx
  packages/react-components/src/components/Alert/Alert.stories.tsx
  packages/react-components/src/components/Avatar/Avatar.spec.tsx
  packages/react-components/src/components/Avatar/Avatar.stories.tsx
  packages/react-components/src/components/Avatar/Avatar.tsx
  packages/react-components/src/components/Badge/Badge.stories.tsx
  packages/react-components/src/components/Button/Button.spec.tsx
  packages/react-components/src/components/Card/Card.stories.tsx
  packages/react-components/src/components/DatePicker/DatePicker.tsx
  packages/react-components/src/components/DatePicker/DatePickerNavbar.tsx
  packages/react-components/src/components/DatePicker/RangeDatePicker.tsx
  packages/react-components/src/components/DatePicker/helpers.ts
  packages/react-components/src/components/DatePicker/types.ts
  packages/react-components/src/components/FormField/FormField.stories.tsx
  packages/react-components/src/components/Input/Input.stories.tsx
  packages/react-components/src/components/Loader/Loader.spec.tsx
  packages/react-components/src/components/Modal/ModalBase.tsx
  packages/react-components/src/components/Modal/ModalPortal.tsx
  packages/react-components/src/components/NumericInput/NumericInput.spec.tsx
  packages/react-components/src/components/NumericInput/NumericInput.stories.tsx
  packages/react-components/src/components/NumericInput/NumericInput.tsx
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/PickerList.tsx
  packages/react-components/src/components/Picker/TriggerBody.spec.tsx
  packages/react-components/src/components/Search/Search.spec.tsx
  packages/react-components/src/components/Search/Search.stories.tsx
  packages/react-components/src/components/SegmentedControl/SegmentedControl.tsx
  packages/react-components/src/components/Switch/Switch.stories.tsx
  packages/react-components/src/components/Switch/Switch.tsx
  packages/react-components/src/components/Tab/Tab.stories.tsx
  packages/react-components/src/components/Tag/Tag.tsx
  packages/react-components/src/components/TagInput/EditableTagContent.tsx
  packages/react-components/src/components/TagInput/TagInput.stories.tsx
  packages/react-components/src/components/Textarea/Textarea.spec.tsx
  packages/react-components/src/components/Textarea/Textarea.stories.tsx
  packages/react-components/src/components/Toast/Toast.stories.tsx
  packages/react-components/src/components/Toast/Toast.tsx
  packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/components/FloatingComponent.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/SpotlightOverlay.tsx
  packages/react-components/src/stories/components/IconsShowcase.tsx
  packages/react-components/src/stories/components/TablerIconsShowcase.tsx
  packages/react-components/tsconfig.json
Labels: dependencies

#707 #697 - ActionMenu - Fix for the issue with opening/hiding the menu
  packages/react-components/src/components/ActionMenu/ActionMenu.spec.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
Labels: bug

#708 #706 - Tab - UI changes for border
  packages/react-components/src/components/Tab/Tab.module.scss
Labels: design
