Repository livechat/design-system, pull requests merged in 2023-11, with the labels that each got.

#875 feat(Popover): Component refactor with FloatingIU
  packages/react-components/src/components/Popover/Popover.mdx
  packages/react-components/src/components/Popover/Popover.module.scss
  packages/react-components/src/components/Popover/Popover.spec.tsx
  packages/react-components/src/components/Popover/Popover.stories.css
  packages/react-components/src/components/Popover/Popover.stories.tsx
  packages/react-components/src/components/Popover/Popover.tsx
  packages/react-components/src/components/Popover/index.ts
  packages/react-components/src/components/Popover/types.ts
Labels: feature

#880 fix(PromoBannerV2): Style fixes
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss
Labels: bug

#881 fix(Alert): Change in buttons align
  packages/react-components/src/components/Alert/Alert.module.scss
  packages/react-components/src/components/Alert/Alert.tsx
Labels: bug

#887 feat(ActionBar): vertical mode, selected item icon if not visible
  packages/react-components/src/components/ActionBar/ActionBar.module.scss
  packages/react-components/src/components/ActionBar/ActionBar.spec.tsx
  packages/react-components/src/components/ActionBar/ActionBar.stories.tsx
  packages/react-components/src/components/ActionBar/ActionBar.tsx
  packages/react-components/src/components/ActionBar/ActionBarItem.tsx
  packages/react-components/src/components/ActionBar/index.ts
  packages/react-components/src/components/ActionBar/types.ts
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/Button/styles/icon.scss
Labels: feature

#890 fix(Icons): Icons update
  packages/icons/entryConfig.ts
  packages/icons/svg/arrow-bar-left.svg
  packages/icons/svg/arrow-bar-right.svg
  packages/icons/svg/text_logo.svg
  packages/icons/svg/text_logo_filled.svg
Labels: design

#892 fix(DetailsCard): Styles fix
  packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
Labels: bug, design

#897 feat[DetailsCard): Added rightNode to pass own element to the label
  packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
  packages/react-components/src/components/DetailsCard/DetailsCard.stories.tsx
  packages/react-components/src/components/DetailsCard/DetailsCard.tsx
Labels: feature

#900 feat(Tooltip): Added flag to set the position strategy
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/Popover/Popover.tsx
  packages/react-components/src/components/Popover/types.ts
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/types.ts
Labels: feature

#904 feat(DetailsCard): Dynamic set max-height of expanded element based on content, added onClick prop to pass own handler on label click
  packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
  packages/react-components/src/components/DetailsCard/DetailsCard.spec.tsx
  packages/react-components/src/components/DetailsCard/DetailsCard.tsx
Labels: feature, design

#908 feat(TransitionTokens): Transition types and duration tokens + new color token
  packages/react-components/.storybook/preview.js
  packages/react-components/src/foundations/transition-token.ts
  packages/react-components/src/foundations/transition.css
  packages/react-components/src/index.scss
  packages/react-components/src/index.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/design-token.ts
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design
