Repository livechat/design-system, pull requests merged in 2024-09, with the labels that each got.

#1294 fix(Picker): make customElement props optional
  packages/react-components/src/components/Picker/components/PickerListItem.tsx
  packages/react-components/src/components/Picker/components/PickerTriggerBody.tsx
  packages/react-components/src/components/Picker/types.ts
Labels: DX

#1295 feat(Input): new AutoComplete component
  packages/react-components/src/components/AutoComplete/AutoComplete.mdx
  packages/react-components/src/components/AutoComplete/AutoComplete.spec.tsx
  packages/react-components/src/components/AutoComplete/AutoComplete.stories.tsx
  packages/react-components/src/components/AutoComplete/AutoComplete.tsx
  packages/react-components/src/components/AutoComplete/helpers.tsx
  packages/react-components/src/components/AutoComplete/index.ts
  packages/react-components/src/components/AutoComplete/types.ts
  packages/react-components/src/components/Input/Input.mdx
  packages/react-components/src/components/Picker/components/PickerList.spec.tsx
  packages/react-components/src/components/Picker/components/PickerList.tsx
  packages/react-components/src/index.ts
Labels: feature

#1313 fix(ActionMenu): change opacity to color token for disabled item
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
Labels: bug

#1314 fix(Tooltip): Arrow position fix
  packages/react-components/src/components/Tooltip/Tooltip.tsx
Labels: bug

#1317 fix(Link): marking bold prop as optional
  packages/react-components/src/components/Link/Link.tsx
Labels: bug

#1318 feat(Icon): add Language icon
  packages/icons/svg/language.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1316 fix(Picker): adding optional inputProps
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/components/PickerTriggerBody.tsx
  packages/react-components/src/components/Picker/types.ts
Labels: feature

#1315 fix(Picker): fixing keyboard handling when search is disabled
  packages/react-components/src/components/AutoComplete/AutoComplete.tsx
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/components/PickerList.spec.tsx
  packages/react-components/src/components/Picker/components/PickerList.tsx
Labels: bug

#1321 feat(Icons): new icons
  packages/icons/svg/engage-filled.svg
  packages/icons/svg/engage.svg
  packages/icons/svg/sparkles-filled.svg
  packages/icons/svg/sparkles.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1319 feat(AppFrame): mobile view and MobileNavigation component
  packages/react-components/src/components/Accordion/Accordion.tsx
  packages/react-components/src/components/Accordion/components/AccordionMultilineElement.tsx
  packages/react-components/src/components/AppFrame/AppFrame.mdx
  packages/react-components/src/components/AppFrame/AppFrame.module.scss
  packages/react-components/src/components/AppFrame/AppFrame.spec.tsx
  packages/react-components/src/components/AppFrame/AppFrame.stories.css
  packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
  packages/react-components/src/components/AppFrame/AppFrame.tsx
  packages/react-components/src/components/AppFrame/components/MobileNavigation/MobileNavigation.module.scss
  packages/react-components/src/components/AppFrame/components/MobileNavigation/MobileNavigation.spec.tsx
  packages/react-components/src/components/AppFrame/components/MobileNavigation/MobileNavigation.tsx
  packages/react-components/src/components/AppFrame/components/MobileNavigation/types.ts
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.module.scss
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.spec.tsx
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.tsx
  packages/react-components/src/components/AppFrame/components/index.ts
  packages/react-components/src/components/AppFrame/stories-helpers.tsx
  packages/react-components/src/components/AppFrame/types.ts
  packages/react-components/src/hooks/helpers.ts
  packages/react-components/src/hooks/index.ts
  packages/react-components/src/hooks/types.ts
  packages/react-components/src/hooks/useHeightResizer.ts
  packages/react-components/src/hooks/useMobileViewDetector.ts
  packages/react-components/src/hooks/useSharedResizeObserver.ts
  packages/react-components/src/providers/AppFrameProvider.tsx
Labels: feature, design

#1351 feat(Button): animated label
  packages/react-components/src/components/Button/Button.helpers.ts
  packages/react-components/src/components/Button/Button.module.scss
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Button/Button.tsx
  packages/react-components/src/components/Button/styles/animated-label.scss
Labels: feature

#1359 feat(Accordion): change label height based on child component
  packages/react-components/src/components/Accordion/Accordion.module.scss
  packages/react-components/src/components/Accordion/Accordion.stories.css
  packages/react-components/src/components/Accordion/components/AccordionAnimatedLabel.module.scss
  packages/react-components/src/components/Accordion/components/AccordionAnimatedLabel.tsx
Labels: feature
