Repository livechat/design-system, pull requests merged in 2024-11, with the labels that each got.

#1423 fix(ProductSwitcher): update Text Accounts name and icon
  packages/react-components/src/components/ProductSwitcher/constants.ts
Labels: High-prio

#1430 feat(Badge): update styles for secondary kind
  packages/react-components/src/components/Badge/Badge.module.scss
  packages/react-components/src/components/Badge/Badge.stories.tsx
  packages/react-components/src/components/Badge/Badge.tsx
Labels: feature

#1433 feat(Icon): add minimize-maximize icons
  packages/icons/svg/arrows_diagonal.svg
  packages/icons/svg/arrows_diagonal_minimize.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1432 feat(Icon): add caret up caret down and multiple choice icons
  packages/icons/svg/caret_down-filled.svg
  packages/icons/svg/caret_down.svg
  packages/icons/svg/caret_up-filled.svg
  packages/icons/svg/caret_up.svg
  packages/icons/svg/multi_choice-filled.svg
  packages/icons/svg/multi_choice.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1435 fix(useAnimations): flag to enable sleep wake scenarios
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
  packages/react-components/src/hooks/useAnimations.ts
  packages/react-components/src/hooks/useSleepWakeSync.ts
Labels: bug

#1434 fix(AppFrame): change button kind for top bar alert warning kind
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
Labels: bug

#1437 feat(Accordion): new promo version
  packages/react-components/src/components/Accordion/Accordion.mdx
  packages/react-components/src/components/Accordion/Accordion.module.scss
  packages/react-components/src/components/Accordion/Accordion.spec.tsx
  packages/react-components/src/components/Accordion/Accordion.stories.css
  packages/react-components/src/components/Accordion/Accordion.stories.tsx
  packages/react-components/src/components/Accordion/Accordion.tsx
  packages/react-components/src/components/Accordion/hooks.ts
  packages/react-components/src/components/Accordion/index.ts
  packages/react-components/src/components/Accordion/types.ts
Labels: feature

#1439 feat(Typography): new semi-bold variant
  packages/react-components/src/components/Typography/Text.tsx
  packages/react-components/src/components/Typography/Typography.module.scss
  packages/react-components/src/stories/foundations/Typography/components/TextExamples.tsx
Labels: feature

#1441 feat(Input): new promo component and tokens update
  packages/react-components/src/components/AutoComplete/types.ts
  packages/react-components/src/components/FormField/FormField.stories.tsx
  packages/react-components/src/components/Input/Input.module.scss
  packages/react-components/src/components/Input/Input.spec.tsx
  packages/react-components/src/components/Input/Input.stories.tsx
  packages/react-components/src/components/Input/Input.tsx
  packages/react-components/src/components/Input/types.ts
  packages/react-components/src/foundations/color-scheme.css
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/foundations/shadow.css
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/light.scss
Labels: feature

#1442 feat(Picker): support 'root' attribute
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/types.ts
Labels: feature, documentation
