Repository livechat/design-system, pull requests merged in 2024-06, with the labels that each got.

#1132 fix(Picker): PickerList height initial value calculation
  package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/components/PickerList.tsx
  packages/react-components/src/components/Picker/constants.ts
  packages/react-components/src/components/Picker/hooks/useFloatingPicker.ts
  packages/react-components/src/components/Picker/types.ts
Labels: bug, dependencies

#1127 fix(ColorTokens): new and updated color tokens
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#1128 fix(DatePicker): prevent infinite update
  packages/react-components/src/components/DatePicker/DatePicker.tsx
Labels: bug

#1129 fix(Tag): change element html tag to prevent button nesting errors
  packages/react-components/src/components/Tag/Tag.tsx
Labels: bug

#1131 fix(Button): plain type hover and active tokens change
  packages/react-components/src/components/Button/styles/kind.scss
Labels: feature, design

#1140 docs(TESTING): docs update
  docs/TESTING.md
Labels: documentation

#1143 fix(ActionBar): tests updates
  packages/react-components/src/components/ActionBar/ActionBar.spec.tsx
  packages/react-components/src/components/ActionBar/ActionBar.tsx
  packages/react-components/src/components/ActionBar/ActionBarItem.spec.tsx
  packages/react-components/src/components/ActionBar/ActionBarItem.tsx
  packages/react-components/src/components/ActionBar/types.ts
Labels: documentation

#1145 fix(ActionMenu): tests updates
  packages/react-components/src/components/ActionMenu/ActionMenu.spec.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/ActionMenu/ActionMenuItem.spec.tsx
  packages/react-components/src/components/ActionMenu/ActionMenuItem.tsx
  packages/react-components/src/components/ActionMenu/types.ts
Labels: documentation

#1146 fix(Alert): tests updates
  packages/react-components/src/components/Alert/Alert.spec.tsx
  packages/react-components/src/components/Alert/Alert.tsx
Labels: documentation

#1148 fix(Switch): tests updates + Loader props spread
  packages/react-components/src/components/Loader/Loader.tsx
  packages/react-components/src/components/Switch/Switch.spec.tsx
  packages/react-components/src/components/Switch/Switch.tsx
Labels: documentation

#1151 fix(DetailsCard): tests updates
  packages/react-components/src/components/DetailsCard/DetailsCard.spec.tsx
Labels: documentation

#1152 fix(Badge): tests updates
  packages/react-components/src/components/Badge/Badge.spec.tsx
  packages/react-components/src/components/Badge/Badge.tsx
Labels: documentation

#1153 fix(Button): tests updates
  packages/react-components/src/components/Button/Button.helpers.spec.ts
  packages/react-components/src/components/Button/Button.helpers.ts
  packages/react-components/src/components/Button/Button.spec.tsx
  packages/react-components/src/components/Button/Button.tsx
Labels: documentation

#1155 fix(Checkbox): tests updates
  packages/react-components/src/components/Checkbox/Checkbox.spec.tsx
Labels: documentation

#1157 fix(Loader): tests updates
  packages/react-components/src/components/Loader/Loader.spec.tsx
  packages/react-components/src/components/Loader/Loader.tsx
Labels: documentation

#1158 fix(Toast): tests updates
  packages/react-components/src/components/Toast/Toast.spec.tsx
Labels: documentation

#1154 fix(Card): tests updates
  packages/react-components/src/components/Card/Card.spec.tsx
  packages/react-components/src/components/Card/Card.tsx
Labels: documentation

#1160 fix(Search): tests updates
  packages/react-components/src/components/Search/Search.spec.tsx
  packages/react-components/src/components/Search/Search.tsx
Labels: documentation

#1162 fix(Textarea): tests updates
  packages/react-components/src/components/Textarea/Textarea.spec.tsx
Labels: documentation

#1161 fix(Input): tests updates
  packages/react-components/src/components/Input/Input.spec.tsx
Labels: documentation

#1169 fix(SegmentedControl): tests updates
  packages/react-components/src/components/SegmentedControl/SegmentedControl.spec.tsx
  packages/react-components/src/components/SegmentedControl/SegmentedControl.tsx
Labels: documentation

#1173 fix(DesignToken): adding new One gradients
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#1172 feat(ActionCard): New component
  packages/react-components/src/components/ActionCard/ActionCard.mdx
  packages/react-components/src/components/ActionCard/ActionCard.module.scss
  packages/react-components/src/components/ActionCard/ActionCard.spec.tsx
  packages/react-components/src/components/ActionCard/ActionCard.stories.tsx
  packages/react-components/src/components/ActionCard/ActionCard.tsx
  packages/react-components/src/components/ActionCard/types.ts
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.mdx
  packages/react-components/src/stories/assets/chat-window.png
Labels: feature

#1168 fix(ActionMenu): fix for the menu height
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenu.spec.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/ActionMenu/stories-constants.tsx
Labels: bug

#1174 feat(Tab): Possibility to add icon to button
  packages/react-components/src/components/Tab/Tab.module.scss
  packages/react-components/src/components/Tab/Tab.stories.tsx
  packages/react-components/src/components/Tab/Tab.tsx
Labels: feature

#1178 fix(Modal): tests updates
  packages/react-components/src/components/Modal/Modal.spec.tsx
  packages/react-components/src/components/Modal/components/ModalBase.spec.tsx
Labels: documentation

#1180 fix(Tooltip): tests updates
  packages/react-components/src/components/Tooltip/Tooltip.helpers.spec.tsx
  packages/react-components/src/components/Tooltip/Tooltip.helpers.ts
  packages/react-components/src/components/Tooltip/Tooltip.spec.tsx
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/components/Info.spec.tsx
  packages/react-components/src/components/Tooltip/components/Info.tsx
  packages/react-components/src/components/Tooltip/components/Interactive.spec.tsx
  packages/react-components/src/components/Tooltip/components/Interactive.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/UserGuideStep.tsx
  packages/react-components/src/components/Tooltip/index.ts
  packages/react-components/src/components/Tooltip/types.ts
Labels: documentation

#1181 fix(FieldGroup): tests updates
  packages/react-components/src/components/FieldGroup/FieldGroup.spec.tsx
Labels: documentation

#1183 fix(PromoBanner): tests updates
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.spec.tsx
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
Labels: documentation

#1184 fix(Tab): tests updates
  packages/react-components/src/components/Tab/Tab.spec.tsx
  packages/react-components/src/components/Tab/Tab.tsx
  packages/react-components/src/components/Tab/TabsWrapper.spec.tsx
  packages/react-components/src/components/Tab/TabsWrapper.tsx
Labels: documentation

#1185 fix(TagInput): tests updates
  packages/react-components/src/components/TagInput/TagInput.spec.tsx
Labels: documentation

#1186 fix(NumericInput): tests updates
  packages/react-components/src/components/NumericInput/NumericInput.spec.tsx
Labels: documentation

#1187 fix(Popover): tests updates
  packages/react-components/src/components/Popover/Popover.spec.tsx
Labels: documentation

#1188 fix(FileUploadProgress): tests updates
  packages/react-components/src/components/FileUploadProgress/FileUploadProgress.spec.tsx
  packages/react-components/src/components/FileUploadProgress/FileUploadProgress.tsx
Labels: documentation

#1191 feat(Interactive): allow all Button props in tooltip button, make secondButton optional
  packages/react-components/src/components/Tooltip/components/Interactive.tsx
  packages/react-components/src/components/Tooltip/types.ts
Labels: feature

#1190 fix(Progress): tests updates
  packages/react-components/src/components/Progress/Progress.helpers.spec.tsx
  packages/react-components/src/components/Progress/Progress.helpers.ts
  packages/react-components/src/components/Progress/ProgressBar.spec.tsx
  packages/react-components/src/components/Progress/ProgressBar.tsx
  packages/react-components/src/components/Progress/ProgressCircle.spec.tsx
  packages/react-components/src/components/Progress/ProgressCircle.tsx
  packages/react-components/src/components/Progress/constants.ts
  packages/react-components/src/components/Progress/helpers.ts
Labels: documentation

#1193 fix(UploadBar): tests updates
  packages/react-components/src/components/UploadBar/UploadBar.module.scss
  packages/react-components/src/components/UploadBar/UploadBar.spec.tsx
  packages/react-components/src/components/UploadBar/UploadBar.tsx
Labels: documentation

#1194 fix(DatePicker): tests updates
  packages/react-components/src/components/DatePicker/DatePicker.spec.tsx
  packages/react-components/src/components/DatePicker/RangeDatePicker.spec.tsx
Labels: documentation

#1195 fix(Picker): tests updates
  packages/react-components/src/components/Picker/Picker.spec.tsx
  packages/react-components/src/components/Picker/components/PickerList.tsx
  packages/react-components/src/components/Picker/components/PickerTrigger.spec.tsx
  packages/react-components/src/components/Picker/components/PickerTrigger.tsx
  packages/react-components/src/components/Picker/components/PickerTriggerBody.spec.tsx
Labels: documentation

#1196 fix(Typography): styles update and new paragraph size
  packages/react-components/src/components/Typography/Typography.module.scss
  packages/react-components/src/components/Typography/types.ts
  packages/react-components/src/stories/foundations/Typography/components/TextExamples.tsx
Labels: bug

#1198 fix(ActionBar): changing start to flex-start values
  packages/react-components/src/components/ActionBar/ActionBar.module.scss
  packages/react-components/src/components/Icon/IconsShowcase/style.scss
Labels: bug

#1209 fix(Tooltip): adding triggerOnHover prop to allow enabling both handlers
  packages/react-components/src/components/Tooltip/Tooltip.spec.tsx
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/types.ts
Labels: bug

#1213 fix(Icons): new icons update
  packages/icons/svg/arrow-autofit-width.svg
  packages/icons/svg/arrow-bar-to-left.svg
  packages/icons/svg/arrow-bar-to-right.svg
  packages/icons/svg/arrows-shuffle.svg
  packages/icons/svg/chart-anomaly.svg
  packages/icons/svg/chatgpt.svg
  packages/icons/svg/directions-sign-off.svg
  packages/icons/svg/directions-sign.svg
  packages/icons/svg/google-sheets.svg
  packages/icons/svg/hubspot.svg
  packages/icons/svg/mailchimp.svg
  packages/icons/svg/stripe.svg
  packages/icons/svg/trending-up.svg
  packages/icons/svg/zoom-in.svg
  packages/icons/svg/zoom-out.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: design

#1212 fix(Color): update color token
  packages/react-components/src/themes/dark.scss
Labels: design

#1218 feat(Icon): add tickets-off icon
  packages/icons/svg/tickets-off.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1216 fix(Picker): onClose, onOpen callbacks fixes
  packages/react-components/src/components/Picker/Picker.spec.tsx
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/hooks/usePickerItems.ts
Labels: bug
