Repository livechat/design-system, pull requests merged in 2024-02, with the labels that each got.

#941 refactor(Picker): Refactoring new Picker component codebase
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/hooks/useFloatingPicker.ts
  packages/react-components/src/components/Picker/hooks/usePickerItems.ts
Labels: feature

#994 fix(Picker): Visibility callbacks, controlled mode; placement prop
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/hooks/useFloatingPicker.ts
  packages/react-components/src/components/Picker/types.ts
  packages/react-components/src/components/Popover/Popover.tsx
Labels: bug, feature

#995 fix(Picker): fix for data controlled mode
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/helpers.ts
  packages/react-components/src/components/Picker/hooks/usePickerItems.ts
Labels: bug

#987 style(Typography): Styles updates for typography components
  packages/react-components/.storybook/preview-head.html
  packages/react-components/src/components/Avatar/Avatar.tsx
  packages/react-components/src/components/Button/styles/base.scss
  packages/react-components/src/components/DatePicker/DatePicker.module.scss
  packages/react-components/src/components/Input/Input.module.scss
  packages/react-components/src/components/Input/Input.tsx
  packages/react-components/src/components/NumericInput/NumericInput.module.scss
  packages/react-components/src/components/Picker/components/PickerListItem.module.scss
  packages/react-components/src/components/Picker/components/PickerListItem.tsx
  packages/react-components/src/components/Picker/components/PickerTrigger.tsx
  packages/react-components/src/components/Picker/components/PickerTriggerBody.module.scss
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.tsx
  packages/react-components/src/components/Search/Search.module.scss
  packages/react-components/src/components/Search/Search.tsx
  packages/react-components/src/components/Tag/Tag.tsx
  packages/react-components/src/components/TagInput/TagInput.module.scss
  packages/react-components/src/components/TagInput/TagInput.tsx
  packages/react-components/src/components/Textarea/Textarea.module.scss
  packages/react-components/src/components/Textarea/Textarea.tsx
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/components/Info.tsx
  packages/react-components/src/components/Tooltip/components/Interactive.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/UserGuideStep.tsx
  packages/react-components/src/components/Typography/Display.tsx
  packages/react-components/src/components/Typography/Heading.tsx
  packages/react-components/src/components/Typography/Text.tsx
  packages/react-components/src/components/Typography/Typography.module.scss
  packages/react-components/src/components/Typography/index.ts
  packages/react-components/src/components/Typography/types.ts
  packages/react-components/src/index.scss
  packages/react-components/src/stories/foundations/Typography/Typography.stories.mdx
  packages/react-components/src/stories/foundations/Typography/components/DisplayExamples.tsx
  packages/react-components/src/stories/foundations/Typography/components/HeadingExamples.tsx
  packages/react-components/src/stories/foundations/Typography/components/TextExamples.tsx
Labels: design

#997 fix(Modal): Possibility to scroll down the overlay if modal is larger than window
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/components/Modal/components/ModalBase.tsx
  packages/react-components/src/utils/StackingContextLevel.scss
Labels: feature, design

#1002 fix(Input): Fixes for typography component usage in Input, TagInput and Textarea
  packages/react-components/src/components/Input/Input.tsx
  packages/react-components/src/components/TagInput/TagInput.tsx
  packages/react-components/src/components/Textarea/Textarea.tsx
Labels: bug

#1004 fix(PromoBanner): Fix memory leak
  packages/react-components/src/components/PromoBanner/PromoBanner.tsx
Labels: bug

#1005 feat(Icons): Add missing ticket priority icons
  packages/icons/README.md
  packages/icons/entryConfig.ts
  packages/icons/package.json
  packages/icons/svg/double_arrow_down.svg
  packages/icons/svg/double_arrow_up.svg
  packages/icons/svg/point-filled.svg
  packages/icons/svg/point.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1000 build(react-components,icons): Tree-shaking for react-components; icons package build improvements
  nx.json
  package-lock.json
  packages/icons/README.md
  packages/icons/entryConfig.ts
  packages/icons/package.json
  packages/icons/scripts/createEntryConfig.js
  packages/icons/scripts/updateExports.js
  packages/icons/tsconfig.json
  packages/icons/vite.config.ts
  packages/react-components/.storybook/main.js
  packages/react-components/README.md
  packages/react-components/package.json
  packages/react-components/src/components/Button/styles/icon.scss
  packages/react-components/src/components/Icon/Icon.tsx
  packages/react-components/src/components/Tab/Tab.tsx
  packages/react-components/vite.config.ts
Labels: feature, dependencies

#1009 fix(Button): add active/focus state to button of high-contrast kind
  packages/react-components/src/components/Button/styles/base.scss
  packages/react-components/src/components/Button/styles/kind.scss
  packages/react-components/src/foundations/shadow.css
Labels: bug

#1013 fix(Icon): Menu icon
  .gitignore
  packages/icons/svg/menu.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1014 fix(build): Reverting tree-shaking components due to css injection issues
  lerna.json
  package-lock.json
  packages/example-react/package.json
  packages/react-components/.storybook/main.js
  packages/react-components/package.json
  packages/react-components/src/components/Modal/components/ModalHeader.tsx
  packages/react-components/src/foundations/index.ts
  packages/react-components/src/index.ts
  packages/react-components/vite.config.ts
Labels: bug, dependencies

#1016 fix(Typography): tokens updates, modal and card components header changes
  packages/react-components/src/components/Card/Card.tsx
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Modal/components/ModalHeader.module.scss
  packages/react-components/src/components/Modal/components/ModalHeader.tsx
  packages/react-components/src/components/Typography/Typography.module.scss
Labels: design

#1017 fix(Color): new tokens, tokens update
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design
