Repository livechat/design-system, pull requests merged in 2024-08, with the labels that each got.

#1269 fix(AppFrame): main nav scrollbar fix for safari
  packages/react-components/src/components/AppFrame/AppFrame.module.scss
  packages/react-components/src/components/AppFrame/AppFrame.stories.css
  packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
  packages/react-components/src/components/AppFrame/components/NavigationGroup/NavigationGroup.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigation/SideNavigation.module.scss
  packages/react-components/src/components/AppFrame/stories-helpers.tsx
Labels: bug, design

#1271 fix(Modal): adding export for ActionModalContent
  packages/react-components/src/components/Modal/index.ts
Labels: bug

#1276 fix(icon): add new Click icon
  packages/icons/svg/click.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1270 feat(OnboardingChecklist): new component
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.mdx
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.module.scss
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.spec.tsx
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.stories.tsx
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.tsx
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.module.scss
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.spec.tsx
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx
  packages/react-components/src/components/OnboardingChecklist/components/index.ts
  packages/react-components/src/components/OnboardingChecklist/index.ts
  packages/react-components/src/components/OnboardingChecklist/types.ts
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/index.ts
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: feature

#1277 feat(AppFrame): Navigation top bar and alerts
  packages/react-components/src/components/AppFrame/AppFrame.mdx
  packages/react-components/src/components/AppFrame/AppFrame.module.scss
  packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.module.scss
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.spec.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/examples.module.scss
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/examples.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/types.ts
  packages/react-components/src/components/AppFrame/components/index.ts
  packages/react-components/src/components/AppFrame/stories-helpers.tsx
Labels: feature, High-prio

#1254 feat(ProductSwitcher): adding new component
  package-lock.json
  packages/icons/svg/text_accounts.svg
  packages/icons/svg/text_logo-full.svg
  packages/icons/svg/text_platform.svg
  packages/react-components/.storybook/main.ts
  packages/react-components/package.json
  packages/react-components/src/components/AppFrame/AppFrame.stories.css
  packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
  packages/react-components/src/components/Popover/types.ts
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.mdx
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.module.scss
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.stories.tsx
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx
  packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.module.scss
  packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx
  packages/react-components/src/components/ProductSwitcher/components/ProductTile/ProductTile.module.scss
  packages/react-components/src/components/ProductSwitcher/components/ProductTile/ProductTile.tsx
  packages/react-components/src/components/ProductSwitcher/constants.ts
  packages/react-components/src/components/ProductSwitcher/helpers.spec.ts
  packages/react-components/src/components/ProductSwitcher/helpers.ts
  packages/react-components/src/components/ProductSwitcher/hooks/useProductSwitcher.ts
  packages/react-components/src/components/ProductSwitcher/index.ts
  packages/react-components/src/components/ProductSwitcher/openwidgetLogoUri.ts
  packages/react-components/src/components/ProductSwitcher/types.ts
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/types.ts
  packages/react-components/src/components/Typography/Text.tsx
  packages/react-components/src/components/Typography/Typography.module.scss
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/index.ts
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
  packages/react-components/vite.config.ts
Labels: feature

#1278 fix(PickerList): styles for no results
  packages/react-components/src/components/Picker/components/PickerList.module.scss
  packages/react-components/src/components/Picker/components/PickerList.tsx
Labels: bug

#1280 fix(OnboardingChecklist): resize observer fix
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx
Labels: bug

#1281 fix(ProductSwitcher): fix typo
  packages/react-components/src/components/ProductSwitcher/constants.ts
Labels: bug

#1279 fix(Colors): adding new color token
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#1285 fix(Icons): replacing home icons with new
  packages/icons/svg/home-filled.svg
  packages/icons/svg/home.svg
Labels: design

#1287 feat(AppFrame): allow `classname` prop in NavigationTopBar
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/types.ts
Labels: feature

#1286 fix(Picker): fixing Picker filtering logic
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/components/PickerTriggerBody.spec.tsx
  packages/react-components/src/components/Picker/components/PickerTriggerBody.tsx
  packages/react-components/src/components/Picker/hooks/usePickerItems.ts
Labels: bug

#1290 fix(AppFrame): Fixes and Improvements
  packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
  packages/react-components/src/components/AppFrame/AppFrame.tsx
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.module.scss
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.tsx
  packages/react-components/src/components/AppFrame/components/NavigationItem/types.ts
  packages/react-components/src/components/AppFrame/stories-helpers.tsx
Labels: bug, feature

#1291 fix(OnboardingChecklist): adding title hint prop
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.stories.tsx
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.tsx
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.module.scss
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx
  packages/react-components/src/components/OnboardingChecklist/types.ts
  packages/react-components/vite.config.ts
Labels: bug

#1297 fix(ProductSwitcher): force dark mode tooltip and different redirect method
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx
  packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx
Labels: bug

#1299 fix(ProductSwitcher): open or focus existing tab
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx
  packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx
  packages/react-components/src/components/ProductSwitcher/helpers.ts
Labels: bug, feature

#1300 fix(OnboardingChecklist): minor fixes
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.module.scss
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx
Labels: bug

#1302 feat(product-switcher): Add UTMs to product redirects; revert open or focus existing tab
  packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.stories.tsx
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx
  packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx
  packages/react-components/src/components/ProductSwitcher/constants.ts
  packages/react-components/src/components/ProductSwitcher/helpers.spec.ts
  packages/react-components/src/components/ProductSwitcher/helpers.ts
  packages/react-components/src/components/ProductSwitcher/hooks/useProductSwitcher.ts
  packages/react-components/src/components/ProductSwitcher/types.ts
Labels: feature, High-prio

#1301 feat(Icon): flag, flag_filled, square_rounded_x
  packages/icons/svg/flag.svg
  packages/icons/svg/flag_filled.svg
  packages/icons/svg/square_rounded_x.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1303 fix(ProductSwitcher): Allow to focus switcher with tab keys
  packages/react-components/src/components/ProductSwitcher/components/ProductTile/ProductTile.tsx
Labels: bug, High-prio

#1304 fix(ProductSwitcher): trail expiring copy change
  packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx
Labels: bug, design

#1305 feat(AppFrame): expiration counter component and fixes
  packages/react-components/src/components/AppFrame/AppFrame.mdx
  packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
  packages/react-components/src/components/AppFrame/components/ExpirationCounter/ExpirationCounter.module.scss
  packages/react-components/src/components/AppFrame/components/ExpirationCounter/ExpirationCounter.spec.tsx
  packages/react-components/src/components/AppFrame/components/ExpirationCounter/ExpirationCounter.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
  packages/react-components/src/components/AppFrame/components/index.ts
Labels: feature

#1306 fix(ProductSwitcher): main tooltip delay on hover
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.module.scss
  packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx
  packages/react-components/src/components/ProductSwitcher/components/ProductTile/ProductTile.module.scss
  packages/react-components/src/components/ProductSwitcher/components/ProductTile/ProductTile.tsx
Labels: design
