Repository livechat/design-system, pull requests merged in 2024-04, with the labels that each got.

#1068 fix(Picker): fixing controlled mode for selected items
  packages/react-components/src/components/Picker/helpers.ts
  packages/react-components/src/components/Picker/hooks/usePickerItems.ts
Labels: bug

#1067 feat(Icon): add icons
  packages/icons/svg/dots-vert.svg
  packages/icons/svg/rosette-discount-check-filled.svg
  packages/icons/svg/rosette-discount-check.svg
  packages/icons/svg/star-filled.svg
  packages/icons/svg/star.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1074 feat(Icon): add trophy icon
  packages/icons/svg/trophy-filled.svg
  packages/icons/svg/trophy.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1076 fix(animations): adding no-animations class
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/foundations/transition.css
Labels: design
