Repository livechat/design-system, pull requests merged in 2024-03, with the labels that each got.

#1018 fix(Color): use root with light theme as default theme
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#1019 fix(Typography): added customColor ad textAlign additional props
  packages/react-components/src/components/Typography/Display.tsx
  packages/react-components/src/components/Typography/Heading.tsx
  packages/react-components/src/components/Typography/Text.tsx
  packages/react-components/src/components/Typography/types.ts
Labels: feature

#1021 fix(Input): change color for disabled state if value is given
  packages/react-components/src/components/Input/Input.module.scss
Labels: bug

#1026 fix(FormField): Docs controls changes, style changes
  packages/react-components/src/components/FormField/FormField.module.scss
  packages/react-components/src/components/FormField/FormField.stories.tsx
  packages/react-components/src/components/FormField/FormField.tsx
Labels: bug

#1031 fix(DesignToken): Adding new tokens; generating token enums with lint-staged
  .husky/pre-commit
  .lintstagedrc
  .lintstagedrc.json
  packages/react-components/package.json
  packages/react-components/scripts/generateDesignTokenEnum.js
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/stories/foundations/Color/Color.stories.mdx
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/stories/foundations/Color/types.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#1025 feat(Skeleton): new component
  packages/react-components/src/components/Skeleton/Skeleton.mdx
  packages/react-components/src/components/Skeleton/Skeleton.module.scss
  packages/react-components/src/components/Skeleton/Skeleton.stories.tsx
  packages/react-components/src/components/Skeleton/SkeletonAvatar.stories.tsx
  packages/react-components/src/components/Skeleton/SkeletonAvatar.tsx
  packages/react-components/src/components/Skeleton/SkeletonText.stories.tsx
  packages/react-components/src/components/Skeleton/SkeletonText.tsx
  packages/react-components/src/components/Skeleton/SkeletonWrapper.tsx
  packages/react-components/src/components/Skeleton/index.ts
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/stories/foundations/Color/Color.stories.mdx
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/stories/foundations/Color/types.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: feature

#1027 fix(Button): Fix the focus state for keyboard control
  packages/react-components/src/components/Button/styles/base.scss
  packages/react-components/src/components/Button/styles/kind.scss
Labels: bug

#1028 feat(TagInput): Passing Tag props to TagInput for tag customisation options
  packages/react-components/src/components/Tag/Tag.stories.tsx
  packages/react-components/src/components/Tag/Tag.tsx
  packages/react-components/src/components/Tag/index.ts
  packages/react-components/src/components/Tag/types.ts
  packages/react-components/src/components/TagInput/TagInput.mdx
  packages/react-components/src/components/TagInput/TagInput.stories.tsx
  packages/react-components/src/components/TagInput/TagInput.tsx
  packages/react-components/src/components/TagInput/components/EditableTag.tsx
  packages/react-components/src/components/TagInput/components/EditableTagContent.tsx
  packages/react-components/src/components/TagInput/components/EmailTagInput.tsx
  packages/react-components/src/components/TagInput/index.ts
  packages/react-components/src/components/TagInput/types.ts
Labels: feature

#1007 feat(Metrics): new Metrics subpackage
  package-lock.json
  packages/metrics/.gitignore
  packages/metrics/README.md
  packages/metrics/package.json
  packages/metrics/src/constants.ts
  packages/metrics/src/flagmanService.ts
  packages/metrics/src/global.d.ts
  packages/metrics/src/index.ts
  packages/metrics/src/metricsGenerator.ts
  packages/metrics/src/tokenScan.ts
  packages/metrics/src/types.ts
  packages/metrics/src/utils.ts
  packages/metrics/tsconfig.json
Labels: feature

#1039 fix(Search): fix for short input container, added ellipsis
  packages/react-components/src/components/Search/Search.module.scss
  packages/react-components/src/components/Search/Search.tsx
Labels: bug

#1041 feat(ActionMenu): Footer prop to display own element in the menu
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenu.spec.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/ActionMenu/types.ts
Labels: feature

#1042 fix(Icons): adding Support and One icons
  packages/icons/svg/one-colored.svg
  packages/icons/svg/support.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1038 fix(DesignToken): Adding new tokens; adding deprecated info to TS enum
  packages/react-components/scripts/generateDesignTokenEnum.js
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/stories/foundations/Color/Color.stories.mdx
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/stories/foundations/Color/types.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: feature, design

#1035 fix(ActionBar): New menu placement logic, styles fixes, docs and stories update
  packages/react-components/src/components/ActionBar/ActionBar.mdx
  packages/react-components/src/components/ActionBar/ActionBar.module.scss
  packages/react-components/src/components/ActionBar/ActionBar.stories.tsx
  packages/react-components/src/components/ActionBar/ActionBar.tsx
  packages/react-components/src/components/ActionBar/ActionBarItem.tsx
  packages/react-components/src/components/ActionBar/constants.tsx
  packages/react-components/src/components/ActionBar/styles/select-indicator.scss
  packages/react-components/src/components/ActionBar/types.ts
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
Labels: feature

#1045 build(Icons): fixing exports for icons
  packages/icons/package.json
Labels: bug, dependencies

#1050 fix(Skeleton): Fix missing export
  packages/react-components/src/index.ts
Labels: bug

#1052 fix(ActionBar): move to components category, UI changes
  packages/react-components/src/components/ActionBar/ActionBar.module.scss
  packages/react-components/src/components/ActionBar/ActionBar.stories.tsx
  packages/react-components/src/components/ActionBar/ActionBar.tsx
  packages/react-components/src/components/ActionBar/ActionBarItem.tsx
  packages/react-components/src/components/ActionBar/constants.tsx
Labels: design

#1057 fix(Modal): added animation on modal show, stories update
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/components/Modal/Modal.stories.tsx
Labels: design

#1056 fix(Picker): list item bug fix
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/components/PickerListItem.tsx
Labels: bug

#1061 fix(Avatar): minHeight and minWidth for avatar
  packages/react-components/src/components/Avatar/Avatar.module.scss
  packages/react-components/src/components/Avatar/Avatar.stories.tsx
  packages/react-components/src/components/Avatar/Avatar.tsx
  packages/react-components/src/components/Avatar/styles/size.scss
  packages/react-components/src/components/Avatar/types.ts
  packages/react-components/src/stories/components/StoryDescriptor.tsx
Labels: bug, design

#1060 fix(Input): fixing missing input focus on wrapper click
  packages/react-components/src/components/Input/Input.module.scss
  packages/react-components/src/components/Input/Input.tsx
Labels: bug
