Repository livechat/design-system, pull requests merged in 2024-10, with the labels that each got.

#1378 fix(ShadowToken): add right and left side tokens
  packages/react-components/src/foundations/shadow-token.ts
  packages/react-components/src/foundations/shadow.css
  packages/react-components/src/stories/foundations/Shadow/constants.ts
Labels: feature

#1385 fix(AppFrame): auto open/close side menu if child element is active
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.spec.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/types.ts
Labels: bug

#1403 fix(AppFrame): top bar styles update and interfaces fix
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.module.scss
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/types.ts
Labels: bug

#1404 build(Chromatic): adding delay to components with animation
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/AutoComplete/AutoComplete.stories.tsx
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Popover/Popover.stories.tsx
  packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
  packages/react-components/src/utils/chromatic-story-helpers.ts
Labels: WIP

#1400 fix(Tooltip): hide when reference is hidden
  package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/AppFrame/AppFrame.stories.css
  packages/react-components/src/components/AppFrame/stories-helpers.tsx
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/types.ts
Labels: bug

#1410 fix(AppFrame): mobile alerts fix and top bar fix
  packages/react-components/src/components/AppFrame/AppFrame.module.scss
  packages/react-components/src/components/AppFrame/AppFrame.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.spec.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
Labels: bug

#1414 fix(AppFrame): nav bar scroll fix and sub nav chevron update
  packages/react-components/src/components/AppFrame/components/NavigationGroup/NavigationGroup.module.scss
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationItem/SideNavigationItem.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationItem/SideNavigationItem.tsx
  packages/react-components/src/components/SearchInput/SearchInput.module.scss
  packages/react-components/src/components/SearchInput/SearchInput.tsx
  packages/react-components/src/hooks/useAnimations.ts
Labels: bug
