Repository livechat/design-system, pull requests merged in 2024-01, with the labels that each got.

#906 refactor(Picker): Refactoring Picker component with FloatingUI
  package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/ActionBar/ActionBar.spec.tsx
  packages/react-components/src/components/Picker/Picker.module.scss
  packages/react-components/src/components/Picker/Picker.spec.tsx
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/PickerList.spec.tsx
  packages/react-components/src/components/Picker/PickerList.tsx
  packages/react-components/src/components/Picker/PickerListItem.tsx
  packages/react-components/src/components/Picker/components/PickerList.module.scss
  packages/react-components/src/components/Picker/components/PickerList.spec.tsx
  packages/react-components/src/components/Picker/components/PickerList.tsx
  packages/react-components/src/components/Picker/components/PickerListItem.module.scss
  packages/react-components/src/components/Picker/components/PickerListItem.tsx
  packages/react-components/src/components/Picker/components/PickerTrigger.module.scss
  packages/react-components/src/components/Picker/components/PickerTrigger.spec.tsx
  packages/react-components/src/components/Picker/components/PickerTrigger.tsx
  packages/react-components/src/components/Picker/components/PickerTriggerBody.module.scss
  packages/react-components/src/components/Picker/components/PickerTriggerBody.spec.tsx
  packages/react-components/src/components/Picker/components/PickerTriggerBody.tsx
  packages/react-components/src/components/Picker/constants.ts
  packages/react-components/src/components/Picker/helpers.ts
  packages/react-components/src/components/Picker/index.ts
  packages/react-components/src/components/Picker/types.ts
  packages/react-components/src/components/Popover/Popover.tsx
  packages/react-components/src/components/Popover/types.ts
  packages/react-components/src/components/Tag/Tag.tsx
Labels: feature

#948 add type attribute to PickerTrigger
  packages/react-components/src/components/Picker/components/PickerTrigger.tsx
Labels: bug

#950 fix(Picker): Fixes for Picker and related components
  packages/react-components/src/components/Picker/components/PickerList.module.scss
  packages/react-components/src/components/Picker/components/PickerListItem.tsx
  packages/react-components/src/components/Picker/components/PickerTrigger.module.scss
  packages/react-components/src/components/Tooltip/Tooltip.tsx
Labels: bug

#953 fix(Alert): move margin to cta container for small and medium sizes
  packages/react-components/src/components/Alert/Alert.module.scss
Labels: bug

#959 fix(Picker): Minor fixes
  packages/icons/package.json
  packages/icons/scripts/updateExports.js
  packages/react-components/src/components/Picker/components/PickerListItem.module.scss
Labels: bug

#952 fix(Button): Styles fixes
  packages/react-components/src/components/Button/styles/icon.scss
Labels: bug

#958 fix(Alert): Close button placement for large container
  packages/react-components/src/components/Alert/Alert.module.scss
  packages/react-components/src/components/Alert/Alert.tsx
Labels: bug

#954 fix(Textarea): overflow hidden for container
  packages/react-components/src/components/Textarea/Textarea.module.scss
Labels: bug

#961 fix(Modal): Fix for the issue with labeled header on small screen
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Modal/components/ModalBase.tsx
Labels: bug

#944 fix(Tooltip): Arrow styles updates
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/Tooltip/helpers.ts
  packages/react-components/src/components/Tooltip/types.ts
  packages/react-components/src/foundations/shadow-token.ts
  packages/react-components/src/foundations/shadow.css
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: bug, design

#967 fix(Avatar): handle emojis as text input
  packages/react-components/src/components/Avatar/Avatar.helpers.spec.ts
  packages/react-components/src/components/Avatar/Avatar.helpers.ts
Labels: bug

#968 fix(Icon): Add new icons
  packages/icons/entryConfig.ts
  packages/icons/package.json
  packages/icons/svg/discount-filled.svg
  packages/icons/svg/discount.svg
Labels: design

#957 docs(ShadowToken): Add docs for Shadow tokens
  packages/react-components/src/stories/Shadow.stories.mdx
  packages/react-components/src/stories/components/Shadow.tsx
  packages/react-components/src/stories/components/ShadowExamples.module.scss
  packages/react-components/src/stories/components/ShadowExamples.tsx
Labels: documentation

#970 fix(Tooltip): tooltip arrow style fix
  packages/react-components/src/components/Tooltip/Tooltip.module.scss
Labels: bug

#971 build(deps-dev): updating get-func-name version
  package-lock.json
Labels: dependencies

#973 fix(components): Adding aria-label to close buttons in components
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/Alert/Alert.tsx
  packages/react-components/src/components/Avatar/Avatar.tsx
  packages/react-components/src/components/Modal/components/ModalCloseButton.tsx
  packages/react-components/src/components/Picker/types.ts
  packages/react-components/src/components/Tag/Tag.tsx
  packages/react-components/src/components/Tooltip/components/Info.tsx
  packages/react-components/src/components/Tooltip/components/Interactive.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/UserGuideStep.tsx
  packages/react-components/src/utils/constants.ts
  packages/react-components/src/utils/index.ts
  packages/react-components/src/utils/types.ts
Labels: bug

#972 build(Storybook): updating storybook and resetting package-lock
  package-lock.json
  packages/react-components/.storybook/main.js
  packages/react-components/package.json
Labels: dependencies

#978 Light/Dark theme visual tests in Chromatic
  package-lock.json
  packages/react-components/.storybook/main.js
  packages/react-components/.storybook/modes.js
  packages/react-components/.storybook/preview-head.html
  packages/react-components/.storybook/preview.js
  packages/react-components/package.json
Labels: documentation

#979 fix(DetailsCard): New animation for card open/close with hidden label mode
  packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
  packages/react-components/src/components/DetailsCard/DetailsCard.spec.tsx
  packages/react-components/src/components/DetailsCard/DetailsCard.tsx
Labels: design

#984 docs(README): Adding separate README for subpackages
  packages/icons/README.md
  packages/react-components/README.md
Labels: documentation

#982 build(PR, commit): Restrict commit message and PR title to CC format
  .commitlintrc.js
  .github/workflows/check-pr-title.yml
  .husky/commit-msg
  package-lock.json
  package.json
Labels: dependencies
