Repository livechat/design-system, pull requests merged in 2024-12, with the labels that each got.

#1445 feat(SelectableCards): new component thumbnail variant
  packages/react-components/src/components/Avatar/Avatar.tsx
  packages/react-components/src/components/SelectableCard/SelectableCard.mdx
  packages/react-components/src/components/SelectableCard/SelectableCard.module.scss
  packages/react-components/src/components/SelectableCard/SelectableCard.spec.tsx
  packages/react-components/src/components/SelectableCard/SelectableCard.stories.css
  packages/react-components/src/components/SelectableCard/SelectableCard.stories.tsx
  packages/react-components/src/components/SelectableCard/SelectableCard.tsx
  packages/react-components/src/components/SelectableCard/components/GallerySelectableCard/GallerySelectableCard.components.tsx
  packages/react-components/src/components/SelectableCard/components/GallerySelectableCard/GallerySelectableCard.module.scss
  packages/react-components/src/components/SelectableCard/components/GallerySelectableCard/GallerySelectableCard.spec.tsx
  packages/react-components/src/components/SelectableCard/components/GallerySelectableCard/GallerySelectableCard.stories.tsx
  packages/react-components/src/components/SelectableCard/components/GallerySelectableCard/GallerySelectableCard.tsx
  packages/react-components/src/components/SelectableCard/components/GallerySelectableCard/types.ts
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/InteractiveGrid/InteractiveGrid.module.scss
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/InteractiveGrid/InteractiveGrid.tsx
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/InteractiveGrid/index.ts
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/InteractiveSelectableCard.components.tsx
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/InteractiveSelectableCard.module.scss
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/InteractiveSelectableCard.spec.tsx
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/InteractiveSelectableCard.stories.tsx
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/InteractiveSelectableCard.tsx
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/types.ts
  packages/react-components/src/components/SelectableCard/components/ThumbnailSelectableCard/ThumbnailSelectableCard.components.tsx
  packages/react-components/src/components/SelectableCard/components/ThumbnailSelectableCard/ThumbnailSelectableCard.module.scss
  packages/react-components/src/components/SelectableCard/components/ThumbnailSelectableCard/ThumbnailSelectableCard.spec.tsx
  packages/react-components/src/components/SelectableCard/components/ThumbnailSelectableCard/ThumbnailSelectableCard.stories.tsx
  packages/react-components/src/components/SelectableCard/components/ThumbnailSelectableCard/ThumbnailSelectableCard.tsx
  packages/react-components/src/components/SelectableCard/components/ThumbnailSelectableCard/types.ts
  packages/react-components/src/components/SelectableCard/components/index.ts
  packages/react-components/src/components/SelectableCard/index.ts
  packages/react-components/src/components/SelectableCard/types.ts
  packages/react-components/src/hooks/index.ts
  packages/react-components/src/hooks/types.ts
  packages/react-components/src/hooks/useInteractive.ts
  packages/react-components/src/index.ts
  packages/react-components/src/utils/types.ts
Labels: feature

#1438 feat(Table): implement table component in Design System
  packages/react-components/src/components/Table/Table.mdx
  packages/react-components/src/components/Table/Table.module.scss
  packages/react-components/src/components/Table/Table.spec.tsx
  packages/react-components/src/components/Table/Table.stories.tsx
  packages/react-components/src/components/Table/Table.tsx
  packages/react-components/src/components/Table/TableBody.spec.tsx
  packages/react-components/src/components/Table/TableBody.tsx
  packages/react-components/src/components/Table/TableHeader.module.scss
  packages/react-components/src/components/Table/TableHeader.spec.tsx
  packages/react-components/src/components/Table/TableHeader.tsx
  packages/react-components/src/components/Table/TableRow.module.scss
  packages/react-components/src/components/Table/TableRow.spec.tsx
  packages/react-components/src/components/Table/TableRow.tsx
  packages/react-components/src/components/Table/hooks.ts
  packages/react-components/src/components/Table/index.ts
  packages/react-components/src/components/Table/stories-constants.tsx
  packages/react-components/src/components/Table/stories-helpers.tsx
  packages/react-components/src/components/Table/styles/pin.scss
  packages/react-components/src/components/Table/styles/size.scss
  packages/react-components/src/components/Table/styles/strips.scss
  packages/react-components/src/components/Table/types.ts
  packages/react-components/src/index.ts
Labels: feature

#1451 fix(docs): removed external links for images and used static
  packages/react-components/src/components/Avatar/Avatar.stories.tsx
  packages/react-components/src/components/Card/Card.module.scss
  packages/react-components/src/components/Card/Card.stories.tsx
  packages/react-components/src/components/InviteAgents/InviteAgents.stories.tsx
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/constants.tsx
  packages/react-components/src/components/Tag/Tag.stories.tsx
  packages/react-components/src/stories/assets/avatar.jpg
  packages/react-components/src/stories/assets/folder.svg
Labels: documentation

#1453 fix(Picker): fix group headers' height and equalise padding
  packages/react-components/src/components/Picker/components/PickerListItem.module.scss
  packages/react-components/src/components/Picker/constants.tsx
Labels: bug

#1460 feat(AiColored, AiOutlined): add new icons
  packages/icons/svg/ai_colored.svg
  packages/icons/svg/ai_outlined.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature
