Repository livechat/design-system, pull requests merged in 2024-07, with the labels that each got.

#1223 fix(Color): token color update
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#1219 feat(ActionBar): logic refactor
  packages/react-components/src/components/ActionBar/ActionBar.module.scss
  packages/react-components/src/components/ActionBar/ActionBar.tsx
  packages/react-components/src/components/ActionBar/ActionBarItem.tsx
  packages/react-components/src/components/ActionBar/constants.tsx
  packages/react-components/src/components/ActionBar/types.ts
Labels: bug

#1230 feat(Icons): add new icon
  packages/icons/svg/plug_connected.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1231 fix(Icons): adding new icon
  packages/icons/svg/layout_sidebar_left.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: design

#1233 fix(Icons): fixing icon name
  packages/icons/svg/plug_connected.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: bug

#1236 build(GithubActions): automatically insert branch name
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/update-pr-description.yml
Labels: dependencies

#1239 fix(icons): add new icon for hello
  packages/icons/svg/hello_colored.svg
  packages/icons/svg/hello_mono.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1224 fix(Modal): animation update, new variant, close button always visible
  packages/react-components/src/components/Modal/Modal.mdx
  packages/react-components/src/components/Modal/Modal.module.scss
  packages/react-components/src/components/Modal/Modal.stories.tsx
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Modal/StoriesComponents.tsx
  packages/react-components/src/components/Modal/components/ActionModalContent.module.scss
  packages/react-components/src/components/Modal/components/ActionModalContent.tsx
Labels: bug, design

#1248 fix(DesignToken): updating tokens; adding new
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/legacy.scss
  packages/react-components/src/themes/light.scss
Labels: design

#1244 fix(Picker): fixing overflow on selected custom elements
  packages/react-components/src/components/Picker/components/PickerListItem.module.scss
  packages/react-components/src/components/Picker/components/PickerListItem.tsx
Labels: bug

#1227 feat(AppFrame): new component
  packages/react-components/src/components/AppFrame/AppFrame.mdx
  packages/react-components/src/components/AppFrame/AppFrame.module.scss
  packages/react-components/src/components/AppFrame/AppFrame.spec.tsx
  packages/react-components/src/components/AppFrame/AppFrame.stories.css
  packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
  packages/react-components/src/components/AppFrame/AppFrame.tsx
  packages/react-components/src/components/AppFrame/components/Navigation/Navigation.module.scss
  packages/react-components/src/components/AppFrame/components/Navigation/Navigation.spec.tsx
  packages/react-components/src/components/AppFrame/components/Navigation/Navigation.tsx
  packages/react-components/src/components/AppFrame/components/Navigation/types.ts
  packages/react-components/src/components/AppFrame/components/NavigationGroup/NavigationGroup.module.scss
  packages/react-components/src/components/AppFrame/components/NavigationGroup/NavigationGroup.spec.tsx
  packages/react-components/src/components/AppFrame/components/NavigationGroup/NavigationGroup.tsx
  packages/react-components/src/components/AppFrame/components/NavigationGroup/types.ts
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.module.scss
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.spec.tsx
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.tsx
  packages/react-components/src/components/AppFrame/components/NavigationItem/types.ts
  packages/react-components/src/components/AppFrame/components/SideNavigation/SideNavigation.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigation/SideNavigation.spec.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigation/SideNavigation.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigation/types.ts
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.spec.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/types.ts
  packages/react-components/src/components/AppFrame/components/SideNavigationItem/SideNavigationItem.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationItem/SideNavigationItem.spec.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationItem/SideNavigationItem.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationItem/constants.ts
  packages/react-components/src/components/AppFrame/components/SideNavigationItem/types.ts
  packages/react-components/src/components/AppFrame/components/index.ts
  packages/react-components/src/components/AppFrame/index.ts
  packages/react-components/src/components/AppFrame/stories-helpers.tsx
  packages/react-components/src/components/AppFrame/types.ts
  packages/react-components/src/foundations/shadow.css
  packages/react-components/src/index.ts
  packages/react-components/src/providers/AppFrameProvider.tsx
  packages/react-components/src/providers/index.ts
Labels: feature

#1256 fix(AppFrame): animations update
  packages/react-components/src/components/AppFrame/AppFrame.module.scss
  packages/react-components/src/components/AppFrame/AppFrame.tsx
  packages/react-components/src/components/AppFrame/components/Navigation/Navigation.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.spec.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.tsx
  packages/react-components/src/components/AppFrame/hooks/useAppFrameAnimations.ts
Labels: design

#1258 feat(Badge): deprecate some props and new UpdateBadge and StatusBadge components
  packages/react-components/src/components/Badge/Badge.stories.tsx
  packages/react-components/src/components/Badge/Badge.tsx
  packages/react-components/src/components/StatusBadge/StatusBadge.module.scss
  packages/react-components/src/components/StatusBadge/StatusBadge.stories.tsx
  packages/react-components/src/components/StatusBadge/StatusBadge.tsx
  packages/react-components/src/components/StatusBadge/index.ts
  packages/react-components/src/components/UpdateBadge/UpdateBadge.module.scss
  packages/react-components/src/components/UpdateBadge/UpdateBadge.stories.tsx
  packages/react-components/src/components/UpdateBadge/UpdateBadge.tsx
  packages/react-components/src/components/UpdateBadge/index.ts
  packages/react-components/src/index.ts
Labels: feature, design

#1260 fix(Picker): fix for event listeners
  packages/react-components/src/components/Picker/components/PickerTrigger.tsx
Labels: bug

#1266 feat(Icon): adding arrows-sort icon
  packages/icons/svg/arrows-sort.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1264 feat(Icon): adding Platform product logo
  packages/icons/svg/platform-colored.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1261 fix(DetailsCard): expand card on label click
  packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
  packages/react-components/src/components/DetailsCard/DetailsCard.spec.tsx
  packages/react-components/src/components/DetailsCard/DetailsCard.tsx
Labels: bug

#1267 fix(Picker): fixed the issue with virtual focus when filtering the list
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/hooks/useFloatingPicker.ts
Labels: bug
