Repository livechat/design-system, pull requests merged in 2025-02, with the labels that each got.

#1506 fix(Button): fix Button text wrapping
  packages/react-components/src/components/Button/styles/base.scss
Labels: bug

#1470 feat(Accordion): moved to emotion styles
  package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/Accordion/Accordion.module.scss
  packages/react-components/src/components/Accordion/Accordion.tsx
  packages/react-components/src/components/Accordion/components/AccordionAnimatedLabel.module.scss
  packages/react-components/src/components/Accordion/components/AccordionAnimatedLabel/AccordionAnimatedLabel.spec.tsx
  packages/react-components/src/components/Accordion/components/AccordionAnimatedLabel/AccordionAnimatedLabel.tsx
  packages/react-components/src/components/Accordion/components/AccordionAnimatedLabel/styles.ts
  packages/react-components/src/components/Accordion/components/AccordionMultilineElement.module.scss
  packages/react-components/src/components/Accordion/components/AccordionMultilineElement/AccordionMultilineElement.tsx
  packages/react-components/src/components/Accordion/components/AccordionMultilineElement/styles.ts
  packages/react-components/src/components/Accordion/components/index.ts
  packages/react-components/src/components/Accordion/helpers.tsx
  packages/react-components/src/components/Accordion/styles.ts
Labels: feature

#1507 feat(ActionCard): add loading state with optional animation
  packages/react-components/src/components/ActionCard/ActionCard.module.scss
  packages/react-components/src/components/ActionCard/ActionCard.spec.tsx
  packages/react-components/src/components/ActionCard/ActionCard.stories.tsx
  packages/react-components/src/components/ActionCard/ActionCard.tsx
  packages/react-components/src/components/ActionCard/types.ts
  packages/react-components/src/components/Skeleton/Skeleton.module.scss
  packages/react-components/src/styles/_animations.scss
Labels: feature

#1509 feat(Picker): add support for toggling dropdown via chevron icon and input field
  packages/react-components/src/components/Picker/Picker.spec.tsx
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/components/PickerTrigger.spec.tsx
  packages/react-components/src/components/Picker/components/PickerTrigger.tsx
Labels: bug

#1514 docs(README): information about migration to emotion
  README.md
Labels: documentation

#1510 fix(Picker): fix clearSearchAfterSelection prop for single type selection
  packages/react-components/src/components/Picker/Picker.spec.tsx
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/hooks/usePickerItems.ts
Labels: bug

#1513 feat(SideNavigationGroup): extend component, make it controllable
  packages/react-components/src/components/AppFrame/AppFrame.mdx
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.spec.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/constants.ts
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/types.ts
  packages/react-components/src/hooks/useAnimations.ts
  packages/react-components/src/index.ts
Labels: feature, documentation

#1523 feat(Shadow, Token): add shadow token and update color tokens
  packages/react-components/src/foundations/shadow-token.ts
  packages/react-components/src/foundations/shadow.css
  packages/react-components/src/stories/foundations/Shadow/constants.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/light.scss
Labels: feature

#1519 fix(AppFrame): add fallback height for older browsers
  packages/react-components/src/components/AppFrame/AppFrame.module.scss
Labels: bug

#1522 fix(FieldField): replace Info icon with Error icon
  packages/react-components/src/components/FieldError/FieldError.tsx
Labels: bug

#1521 docs(Skeleton): add example of SkeletonText with custom width
  packages/react-components/src/components/Skeleton/Skeleton.mdx
  packages/react-components/src/components/Skeleton/SkeletonText.stories.tsx
Labels: documentation

#1525 feat(SegmentedControl): add support for icon-only buttons
  packages/react-components/src/components/SegmentedControl/SegmentedControl.stories.tsx
  packages/react-components/src/components/SegmentedControl/SegmentedControl.tsx
Labels: feature

#1530 docs(Popover, Tooltip): disable transitions in Chromatic tests
  packages/react-components/src/components/Popover/Popover.stories.tsx
  packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
Labels: documentation

#1527 docs(FormField): add example of character counter implementation
  packages/react-components/src/components/FormField/FormField.mdx
  packages/react-components/src/components/FormField/FormField.stories.tsx
Labels: documentation

#1532 fix(UserGuide): fix sizing for images and videos
  packages/react-components/src/components/UserGuide/UserGuide.module.scss
  packages/react-components/src/components/UserGuide/UserGuide.stories.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideStep/UserGuideStep.module.scss
  packages/react-components/src/components/UserGuide/components/UserGuideStep/UserGuideStep.tsx
Labels: bug, high

#1526 fix(PromoBannerV2): add aria-label to close button for improved accessibility
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
Labels: bug

#1516 feat(Button): remove 'basic' button kind from stories and add depreciation note
  packages/react-components/src/components/Button/Button.mdx
  packages/react-components/src/components/Button/Button.stories.tsx
  packages/react-components/src/components/Button/Button.tsx
Labels: feature, documentation

#1550 refactor(ActionMenu): migrate to emotion
  packages/react-components/.storybook/preview.js
  packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
  packages/react-components/src/components/ActionMenu/ActionMenu.tsx
  packages/react-components/src/components/ActionMenu/styles.ts
  packages/react-components/src/foundations/index.ts
  packages/react-components/src/foundations/stacking-context-level.css
  packages/react-components/src/foundations/stacking-context-level.ts
Labels: DX

#1540 refactor(ActionBar): migrate styles to emotion
  packages/react-components/src/components/ActionBar/ActionBar.module.scss
  packages/react-components/src/components/ActionBar/ActionBar.tsx
  packages/react-components/src/components/ActionBar/ActionBarItem.tsx
  packages/react-components/src/components/ActionBar/styles.ts
  packages/react-components/src/components/ActionBar/styles/select-indicator.scss
Labels: DX

#1557 refactor(Skeleton): migrate from SCSS to Emotion CSS
  packages/react-components/src/components/Skeleton/Skeleton.module.scss
  packages/react-components/src/components/Skeleton/SkeletonAvatar.tsx
  packages/react-components/src/components/Skeleton/SkeletonText.tsx
  packages/react-components/src/components/Skeleton/SkeletonWrapper.tsx
  packages/react-components/src/components/Skeleton/styles.ts
Labels: DX

#1561 refactor(OverflowTooltipText): refactor styles to emotion
  packages/react-components/src/components/OverflowTooltipText/OverflowTooltipText.module.scss
  packages/react-components/src/components/OverflowTooltipText/OverflowTooltipText.tsx
  packages/react-components/src/components/OverflowTooltipText/styles.ts
Labels: DX

#1565 refactor(Progress, UploadBar): migrate to emotion
  packages/react-components/src/components/Progress/ProgressBar.module.scss
  packages/react-components/src/components/Progress/ProgressBar.tsx
  packages/react-components/src/components/Progress/ProgressCircle.module.scss
  packages/react-components/src/components/Progress/ProgressCircle.tsx
  packages/react-components/src/components/Progress/styles.ts
  packages/react-components/src/components/UploadBar/UploadBar.module.scss
  packages/react-components/src/components/UploadBar/UploadBar.tsx
  packages/react-components/src/components/UploadBar/styles.ts
Labels: DX

#1531 feat(Table): add multi-select table type with styling updates
  packages/react-components/src/components/Button/styles/kind.scss
  packages/react-components/src/components/Table/Table.module.scss
  packages/react-components/src/components/Table/Table.stories.tsx
  packages/react-components/src/components/Table/Table.tsx
  packages/react-components/src/components/Table/TableHeader.module.scss
  packages/react-components/src/components/Table/TableHeader.spec.tsx
  packages/react-components/src/components/Table/TableHeader.tsx
  packages/react-components/src/components/Table/TableRow.module.scss
  packages/react-components/src/components/Table/TableRow.tsx
  packages/react-components/src/components/Table/stories-helpers.tsx
  packages/react-components/src/components/Table/types.ts
Labels: feature

#1571 refactor(PromoBannerV2): migrate to emotion
  .github/workflows/chromatic.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.spec.tsx
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.css
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.styles.ts
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.tsx
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
  packages/react-components/src/components/PromoBannerV2/index.ts
  packages/react-components/src/components/PromoBannerV2/styles.ts
  packages/react-components/src/components/PromoBannerV2/types.ts
Labels: DX

#1573 refactor(Loader): migrate from CSS modules to emotion
  packages/react-components/src/components/Loader/Loader.module.scss
  packages/react-components/src/components/Loader/Loader.spec.tsx
  packages/react-components/src/components/Loader/Loader.stories.tsx
  packages/react-components/src/components/Loader/Loader.tsx
  packages/react-components/src/components/Loader/styles.ts
  packages/react-components/src/components/Loader/types.ts
Labels: DX

#1572 refactor(ListItem): migrate from CSS modules to emotion
  packages/react-components/src/components/ListItem/ListItem.module.scss
  packages/react-components/src/components/ListItem/ListItem.tsx
  packages/react-components/src/components/ListItem/styles.ts
Labels: DX

#1570 refactor(Link): migrate from SCSS modules to emotion
  packages/react-components/src/components/Link/Link.module.scss
  packages/react-components/src/components/Link/Link.tsx
  packages/react-components/src/components/Link/styles.ts
Labels: DX

#1579 docs(Storybook): rename stories CSS files and fix chromatic
  packages/react-components/src/components/Accordion/Accordion.stories.tsx
  packages/react-components/src/components/Accordion/AccordionStories.css
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenuStories.css
  packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
  packages/react-components/src/components/AppFrame/AppFrameStories.css
  packages/react-components/src/components/AppFrame/stories-helpers.tsx
  packages/react-components/src/components/DetailsCard/DetailsCard.stories.tsx
  packages/react-components/src/components/DetailsCard/DetailsCardStories.css
  packages/react-components/src/components/EmptyState/EmptyState.stories.tsx
  packages/react-components/src/components/ListItem/ListItem.stories.tsx
  packages/react-components/src/components/ListItem/ListItemStories.css
  packages/react-components/src/components/Modal/ModalStories.css
  packages/react-components/src/components/Modal/StoriesComponents.tsx
  packages/react-components/src/components/OverflowTooltipText/OverflowTooltipText.stories.tsx
  packages/react-components/src/components/OverflowTooltipText/OverflowTooltipTextStories.css
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/PickerStories.css
  packages/react-components/src/components/Popover/Popover.stories.tsx
  packages/react-components/src/components/Popover/PopoverStories.css
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.tsx
  packages/react-components/src/components/PromoBannerV2/PromoBannerV2Stories.css
  packages/react-components/src/components/SelectableCard/SelectableCard.stories.tsx
  packages/react-components/src/components/SelectableCard/SelectableCardStories.css
  packages/react-components/src/components/SelectableCard/components/GallerySelectableCard/GallerySelectableCard.stories.tsx
  packages/react-components/src/components/SelectableCard/components/InteractiveSelectableCard/InteractiveSelectableCard.stories.tsx
  packages/react-components/src/components/SelectableCard/components/ThumbnailSelectableCard/ThumbnailSelectableCard.stories.tsx
  packages/react-components/src/components/Table/TableRow.tsx
  packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
  packages/react-components/src/components/Tooltip/TooltipStories.css
  packages/react-components/src/components/UserGuide/UserGuide.stories.tsx
  packages/react-components/src/components/UserGuide/UserGuideStories.css
Labels: DX

#1585 feat(RangeDatePickerV2): display selected predefined filter
  packages/react-components/src/components/RangeDatePickerV2/RangeDatePickerV2.tsx
  packages/react-components/src/components/RangeDatePickerV2/components/RangeDatePickerV2Label.tsx
Labels: feature

#1580 feat(OnboardingChecklist): new prop for custom content to list item
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.stories.tsx
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.tsx
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklistStories.css
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx
  packages/react-components/src/components/OnboardingChecklist/types.ts
Labels: feature

#1584 feat(UserGuide): ui changes
  packages/react-components/src/components/UserGuide/UserGuide.stories.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/UserGuideBubbleStep.module.scss
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/UserGuideBubbleStep.spec.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/UserGuideBubbleStep.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/types.ts
  packages/react-components/src/components/UserGuide/components/UserGuideStep/UserGuideStep.module.scss
  packages/react-components/src/components/UserGuide/components/UserGuideStep/UserGuideStep.spec.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideStep/UserGuideStep.tsx
Labels: feature

#1586 fix(AnimatedTextContainer): script fix
  packages/react-components/src/components/AnimatedTextContainer/AnimatedTextContainer.tsx
Labels: bug

#1591 feat(Picker): add avatar variations to Picker component
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/components/PickerListItem.tsx
  packages/react-components/src/components/Picker/types.ts
Labels: feature

#1589 feat(AppFrame): ui update for light mode
  packages/react-components/src/components/AppFrame/AppFrame.module.scss
  packages/react-components/src/components/AppFrame/AppFrame.tsx
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.module.scss
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.tsx
  packages/react-components/src/components/AppFrame/components/SideNavigation/SideNavigation.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.module.scss
  packages/react-components/src/components/AppFrame/components/SideNavigationItem/SideNavigationItem.module.scss
  packages/react-components/src/components/AppFrame/stories-helpers.tsx
  packages/react-components/src/themes/light.scss
Labels: feature, design

#1605 feat(Accordion): new prop
  packages/react-components/src/components/Accordion/Accordion.module.scss
  packages/react-components/src/components/Accordion/Accordion.stories.tsx
  packages/react-components/src/components/Accordion/Accordion.tsx
  packages/react-components/src/components/Accordion/AccordionStories.css
  packages/react-components/src/components/Accordion/types.ts
Labels: feature

#1600 feat(Icon): add book filled icon
  packages/icons/svg/book-filled.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1602 feat(UserGuideStep): add className prop and fixed default width
  packages/react-components/src/assets/onboarding_final.mp4
  packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
  packages/react-components/src/components/UserGuide/UserGuide.mdx
  packages/react-components/src/components/UserGuide/UserGuide.stories.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/UserGuideBubbleStep.module.scss
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/UserGuideBubbleStep.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/types.ts
  packages/react-components/src/components/UserGuide/components/UserGuideStep/UserGuideStep.module.scss
Labels: feature

#1607 fix(UserGuide): adjusted x placing for first and last step
  packages/react-components/src/components/UserGuide/UserGuide.tsx
Labels: bug
