Repository livechat/design-system, pull requests merged in 2025-01, with the labels that each got.

#1455 feat(DatePicker): lib update and related changes
  package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/DatePicker/DatePicker.mdx
  packages/react-components/src/components/DatePicker/DatePicker.module.scss
  packages/react-components/src/components/DatePicker/DatePicker.spec.tsx
  packages/react-components/src/components/DatePicker/DatePicker.stories.tsx
  packages/react-components/src/components/DatePicker/DatePicker.tsx
  packages/react-components/src/components/DatePicker/DatePickerNavbar.tsx
  packages/react-components/src/components/DatePicker/RangeDatePicker.spec.tsx
  packages/react-components/src/components/DatePicker/RangeDatePicker.tsx
  packages/react-components/src/components/DatePicker/components/DatePickerCustomNavigation.module.scss
  packages/react-components/src/components/DatePicker/components/DatePickerCustomNavigation.tsx
  packages/react-components/src/components/DatePicker/helpers.ts
  packages/react-components/src/components/DatePicker/types.ts
  packages/react-components/src/components/PromoBanner/PromoBanner.stories.tsx
Labels: feature, dependencies

#1468 feat(Popover): add animation
  packages/react-components/src/components/Popover/Popover.stories.tsx
  packages/react-components/src/components/Popover/Popover.tsx
  packages/react-components/src/components/Popover/types.ts
Labels: feature

#1461 feat(OverflowTooltipText): add new component
  packages/react-components/src/components/OverflowTooltipText/OverflowTooltipText.mdx
  packages/react-components/src/components/OverflowTooltipText/OverflowTooltipText.module.scss
  packages/react-components/src/components/OverflowTooltipText/OverflowTooltipText.stories.css
  packages/react-components/src/components/OverflowTooltipText/OverflowTooltipText.stories.tsx
  packages/react-components/src/components/OverflowTooltipText/OverflowTooltipText.tsx
  packages/react-components/src/components/OverflowTooltipText/index.ts
  packages/react-components/src/components/OverflowTooltipText/types.ts
  packages/react-components/src/hooks/index.ts
  packages/react-components/src/hooks/types.ts
  packages/react-components/src/hooks/useIsOverflow.ts
  packages/react-components/src/hooks/useOnHover.ts
  packages/react-components/src/index.ts
Labels: feature

#1457 refactor(ActionMenuItem): expose ActionMenuItem as a standalone component ListItem
  packages/react-components/src/components/ActionBar/ActionBar.tsx
  packages/react-components/src/components/ActionMenu/ActionMenu.mdx
  packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
  packages/react-components/src/components/ActionMenu/ActionMenuItem.tsx
  packages/react-components/src/components/ActionMenu/index.ts
  packages/react-components/src/components/ActionMenu/stories-constants.tsx
  packages/react-components/src/components/ActionMenu/types.ts
  packages/react-components/src/components/InviteAgents/InviteAgents.tsx
  packages/react-components/src/components/ListItem/ListItem.mdx
  packages/react-components/src/components/ListItem/ListItem.module.scss
  packages/react-components/src/components/ListItem/ListItem.spec.tsx
  packages/react-components/src/components/ListItem/ListItem.stories.css
  packages/react-components/src/components/ListItem/ListItem.stories.tsx
  packages/react-components/src/components/ListItem/ListItem.tsx
  packages/react-components/src/components/ListItem/index.ts
  packages/react-components/src/components/ListItem/types.ts
  packages/react-components/src/index.ts
Labels: documentation

#1476 fix(DatePicker): wrapper with min width
  packages/react-components/src/components/DatePicker/DatePicker.module.scss
  packages/react-components/src/components/DatePicker/DatePicker.tsx
Labels: bug

#1479 fix(Input): make types exportable
  packages/react-components/src/components/Input/index.ts
Labels: bug

#1480 fix(DatePicker): correct styles for range date picker
  packages/react-components/src/components/DatePicker/DatePicker.module.scss
  packages/react-components/src/components/DatePicker/RangeDatePicker.tsx
  packages/react-components/src/components/DatePicker/hooks.ts
  packages/react-components/src/components/DatePicker/types.ts
Labels: bug

#1464 feat(RangeDatePickerV2): new variant of component
  packages/react-components/src/components/DatePicker/DatePicker.module.scss
  packages/react-components/src/components/DatePicker/RangeDatePicker.tsx
  packages/react-components/src/components/DatePicker/helpers.ts
  packages/react-components/src/components/DatePicker/hooks.ts
  packages/react-components/src/components/DatePicker/types.ts
  packages/react-components/src/components/RangeDatePickerV2/RangeDatePickerV2.mdx
  packages/react-components/src/components/RangeDatePickerV2/RangeDatePickerV2.module.scss
  packages/react-components/src/components/RangeDatePickerV2/RangeDatePickerV2.spec.tsx
  packages/react-components/src/components/RangeDatePickerV2/RangeDatePickerV2.stories.tsx
  packages/react-components/src/components/RangeDatePickerV2/RangeDatePickerV2.tsx
  packages/react-components/src/components/RangeDatePickerV2/components/RangeDatePickerV2Label.module.scss
  packages/react-components/src/components/RangeDatePickerV2/components/RangeDatePickerV2Label.tsx
  packages/react-components/src/components/RangeDatePickerV2/helpers.ts
  packages/react-components/src/components/RangeDatePickerV2/index.ts
  packages/react-components/src/components/RangeDatePickerV2/types.ts
  packages/react-components/src/index.ts
Labels: feature

#1489 feat(Checkbox): add indeterminate state and update old styles
  packages/react-components/src/components/Checkbox/Checkbox.module.scss
  packages/react-components/src/components/Checkbox/Checkbox.stories.tsx
  packages/react-components/src/components/Checkbox/Checkbox.tsx
Labels: feature, High-prio

#1490 feat(Tokens): add new color and shadow tokens
  packages/react-components/src/foundations/design-token.ts
  packages/react-components/src/foundations/shadow-token.ts
  packages/react-components/src/foundations/shadow.css
  packages/react-components/src/stories/foundations/Color/Color.mdx
  packages/react-components/src/stories/foundations/Color/data.ts
  packages/react-components/src/stories/foundations/Color/types.ts
  packages/react-components/src/stories/foundations/Shadow/constants.ts
  packages/react-components/src/themes/dark.scss
  packages/react-components/src/themes/light.scss
Labels: feature, High-prio

#1488 fix(OnboardingChecklist): UI updates
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.module.scss
  packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.tsx
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.module.scss
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.spec.tsx
  packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx
  packages/react-components/src/components/OnboardingChecklist/types.ts
Labels: design

#1494 fix(LegacyModal): fix legacy modal message
  docs/customized-components/Menu.js
Labels: documentation

#1491 feat(EmptyState): add EmptyState component
  packages/react-components/src/components/EmptyState/EmptyState.mdx
  packages/react-components/src/components/EmptyState/EmptyState.module.scss
  packages/react-components/src/components/EmptyState/EmptyState.spec.tsx
  packages/react-components/src/components/EmptyState/EmptyState.stories.module.scss
  packages/react-components/src/components/EmptyState/EmptyState.stories.tsx
  packages/react-components/src/components/EmptyState/EmptyState.tsx
  packages/react-components/src/components/EmptyState/index.ts
  packages/react-components/src/components/EmptyState/types.ts
  packages/react-components/src/index.ts
Labels: feature, High-prio

#1495 feat(FormField): add boldLabel prop for InputPromo
  packages/react-components/src/components/FormField/FormField.module.scss
  packages/react-components/src/components/FormField/FormField.stories.tsx
  packages/react-components/src/components/FormField/FormField.tsx
Labels: feature, High-prio

#1500 feat(stepper): added stepper component
  packages/react-components/src/components/Stepper/Stepper.module.scss
  packages/react-components/src/components/Stepper/Stepper.spec.tsx
  packages/react-components/src/components/Stepper/Stepper.stories.tsx
  packages/react-components/src/components/Stepper/Stepper.tsx
  packages/react-components/src/components/Stepper/index.ts
  packages/react-components/src/components/Stepper/types.ts
  packages/react-components/src/index.ts
Labels: feature

#1504 feat(Icons): add new icon WhatsAppColored
  packages/icons/svg/whats-app-colored.svg
  packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Labels: feature

#1497 feat(FormField, Input, NumericInput, TagInput, Picker, Textarea, Autocomplete): add readonly state
  packages/react-components/src/components/AutoComplete/AutoComplete.stories.tsx
  packages/react-components/src/components/AutoComplete/AutoComplete.tsx
  packages/react-components/src/components/AutoComplete/types.ts
  packages/react-components/src/components/Checkbox/Checkbox.module.scss
  packages/react-components/src/components/Checkbox/Checkbox.stories.tsx
  packages/react-components/src/components/Checkbox/Checkbox.tsx
  packages/react-components/src/components/FormField/FormField.module.scss
  packages/react-components/src/components/FormField/FormField.stories.tsx
  packages/react-components/src/components/FormField/FormField.tsx
  packages/react-components/src/components/Input/Input.module.scss
  packages/react-components/src/components/Input/Input.stories.tsx
  packages/react-components/src/components/Input/Input.tsx
  packages/react-components/src/components/Input/types.ts
  packages/react-components/src/components/NumericInput/NumericInput.stories.tsx
  packages/react-components/src/components/NumericInput/NumericInput.tsx
  packages/react-components/src/components/Picker/Picker.stories.tsx
  packages/react-components/src/components/Picker/Picker.tsx
  packages/react-components/src/components/Picker/types.ts
  packages/react-components/src/components/RadioButton/RadioButton.module.scss
  packages/react-components/src/components/RadioButton/RadioButton.stories.tsx
  packages/react-components/src/components/RadioButton/RadioButton.tsx
  packages/react-components/src/components/ReadOnlyText/ReadOnlyText.tsx
  packages/react-components/src/components/ReadOnlyText/index.ts
  packages/react-components/src/components/TagInput/TagInput.stories.tsx
  packages/react-components/src/components/TagInput/TagInput.tsx
  packages/react-components/src/components/TagInput/types.ts
  packages/react-components/src/components/Textarea/Textarea.stories.tsx
  packages/react-components/src/components/Textarea/Textarea.tsx
  packages/react-components/src/providers/ReadOnlyFormFieldProvider.tsx
Labels: feature, High-prio

#1487 feat(UserGuide): update UserGuide component with new highlight functionality
  .stylelintrc.json
  packages/react-components/src/components/ActionBar/ActionBar.tsx
  packages/react-components/src/components/AnimatedTextContainer/AnimatedTextContainer.mdx
  packages/react-components/src/components/AnimatedTextContainer/AnimatedTextContainer.stories.tsx
  packages/react-components/src/components/AnimatedTextContainer/AnimatedTextContainer.tsx
  packages/react-components/src/components/AnimatedTextContainer/index.ts
  packages/react-components/src/components/AnimatedTextContainer/types.ts
  packages/react-components/src/components/AppFrame/components/ExpirationCounter/ExpirationCounter.tsx
  packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
  packages/react-components/src/components/AppFrame/components/NavigationTopBar/examples.tsx
  packages/react-components/src/components/AppFrame/stories-helpers.tsx
  packages/react-components/src/components/Tooltip/Tooltip.mdx
  packages/react-components/src/components/Tooltip/Tooltip.stories.css
  packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/SpotlightOverlay.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/UserGuide.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/UserGuideStep.tsx
  packages/react-components/src/components/Tooltip/components/UserGuide/index.ts
  packages/react-components/src/components/Tooltip/components/index.ts
  packages/react-components/src/components/Tooltip/index.ts
  packages/react-components/src/components/UserGuide/UserGuide.mdx
  packages/react-components/src/components/UserGuide/UserGuide.module.scss
  packages/react-components/src/components/UserGuide/UserGuide.stories.css
  packages/react-components/src/components/UserGuide/UserGuide.stories.tsx
  packages/react-components/src/components/UserGuide/UserGuide.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/UserGuideBubbleStep.module.scss
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/UserGuideBubbleStep.spec.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/UserGuideBubbleStep.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideBubbleStep/types.ts
  packages/react-components/src/components/UserGuide/components/UserGuideStep/UserGuideStep.module.scss
  packages/react-components/src/components/UserGuide/components/UserGuideStep/UserGuideStep.spec.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideStep/UserGuideStep.tsx
  packages/react-components/src/components/UserGuide/components/UserGuideStep/types.ts
  packages/react-components/src/components/UserGuide/components/index.ts
  packages/react-components/src/components/UserGuide/index.ts
  packages/react-components/src/components/UserGuide/placeholder.png
  packages/react-components/src/components/UserGuide/stories-helpers.css
  packages/react-components/src/components/UserGuide/stories-helpers.tsx
  packages/react-components/src/components/UserGuide/styles/transitions.scss
  packages/react-components/src/components/UserGuide/types.ts
  packages/react-components/src/components/UserGuide/virtualElementReference.ts
  packages/react-components/src/foundations/shadow.css
  packages/react-components/src/foundations/transition.css
  packages/react-components/src/index.ts
  packages/react-components/src/stories/assets/cursor.svg
  packages/react-components/src/utils/types.ts
Labels: feature, design
